### ISSUE TITLE
Handling Control Characters

### ISSUE THREAD

**Issue by o0-o** [rclone/rclone#1580]
Hi, I'm running rclone 1.3.6 on CentOS 7. I am syncing to Google Drive.

I'm running into the error "Can't store file with control characters" because my client has several files with a tab in the filename. rclone is seeing the tab (appropriately) as \t and throwing the error.

Is it possible to handle some/all of the control characters with replacements (some spaces in place of a \t for instance)? Maybe have control character conversion as an option when running the command? I really don't care what it replaces it with, I just need the files to get pushed to gdrive.

Also, while these files do throw a message to stdout when running the command, they do not count as errors in the "Transferred:  Errors: Checks:" etc. If it is not possible to convert control characters to something benign, can we count them as errors, as they are files that fail to sync? Currently, you could run the command, see Erros: 0 and assume everything synced/uploaded when in fact it did not.

I am handling this manually now, so not urgent. Thank you for your great work on rclone! It is an amazing tool.

**Comment by ncw** [comment]
Not all remotes can store control characters (but some can).

I have a plan to fix this by transforming the control characters into a unicode equivalent.

So characters 0-31,127 (excluding space) would become
  - ␀␁␂␃␄␅␆␇␈␉␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟␠
  - ␡

The current behavior of just ignoring the control characters is mostly to ignore the `Icon\r` files macos is fond of leaving about the place!

I could add a flag `--local-no-skip-control-chars` or something like that which would work for copying to drive since the only character drive can't have in a name is 0x00.

**Comment by johnclendenen** [comment]
Sounds good, any solution is fine with me. I have 100s of files with a \t in the filename and I need to get them on drive one way or another.

Thanks for your hard work

**Comment by jikamens** [comment]
In regards to this, I am a little confused about the fact that I get the "NOTICE: Local file system at ...: Can't store file with control characters: ".../Icon\r" when doing `rclone ls` on a local directory. This is confusing for two reasons:

1. I'm not trying to _store_ anything, I'm _listing_ the files in the local filesystem.

2. Given that there _are_, in fact, files with control characters stored in the local filesystem, the error message's claim that such files cannot be stored is, um, wrong on its face. _They are already stored._

**Comment by jikamens** [comment]
Also, I would gladly avoid this issue in the short term by filtering these files out, but alas I cannot find any filter expression that will match paths ending in "/Icon\r". Or, more accurately, who knows, maybe my filter expressions are matching, but rclone is still generating the warnings about control characters in the name.

**Comment by jikamens** [comment]
Above issue (warnings about filtered files) split off into #1646.

**Comment by dotdigital-digital** [comment]
@ncw wanted to circle back on this. I am almost done with a multi-terabyte upload that's taken almost a year. Soon, all that will be left are the files with control characters in the name.

I saw you added this to the "Soon" milestone back in August. What are the chances we'll see this by 2018?

If you haven't got the time for it, that's totally fine. I can go in and remove the control characters, but if an update is in the works, I'll happily wait for it.

Thanks

**Comment by ncw** [comment]
> If you haven't got the time for it, that's totally fine. I can go in and remove the control characters, but if an update is in the works, I'll happily wait for it.

I'm not working on it at the moment, though rclone is moving in the right direction :-)

If you want this done by 2018 then you should probably rename the control chars!

**Comment by fidonet** [comment]
apologies for resurrecting this one, but it's now nearly 2019 ... did this feature end up being added?  It seems not?

I'm trying to sync 50+TB of data and there are an awful lot of those errors flying past as I go from a local HFS+ file system to a Samba file system on a QNAP NAS

I'm concerned at what might end up being missed in the sync as a result :(

**Comment by ncw** [comment]
@fidonet actually this feature is in progress at the moment - @B4dM4n is working on fixing this once and for all along the lines above. It is a big change which we'll probably land in the next few weeks.

**Comment by o0-o** [comment]
Was this implemented? I don't see any open pull requests from @B4dM4n

**Comment by ncw** [comment]
> Was this implemented? I don't see any open pull requests from @B4dM4n

No, me neither! We've merged the first step of this, I suspect @B4dM4n has the rest in a not quite finished or submitted state.

**Comment by RomeSilvanus** [comment]
I actually have a program that generates files with " \t" in them also. Trying to copy them to GDrive. 
It would be nice for rclone to be able to handle it. (Plus I can't find any info on how to make a script to find and remove this character anywhere :c )

**Comment by pkiula** [comment]
Same here. Still getting the `Icon\r` messages in August 2019. Please fix this! Mac OSX here. Thanks.

**Comment by ncw** [comment]
This will be fixed in #3148 which I'm hoping to land for v1.49

**Comment by motin** [comment]
> This will be fixed in #3148 which I'm hoping to land for v1.49

Did this land in 1.49.5? I am using 1.49.5 on OSX and the issue of not being able to store files with control characters remains. Pops up with the infamous Icon\r as well as when there are tabs and newlines in filenames, even when copying from local to local. 

Also, I find no way to exclude `Icon\r`. Neither `--exclude='Icon*'`, `--exclude='Icon?'`, `--exclude='Icon\r`, `--exclude='Icon\\r` nor ` --exclude='Icon'$'\r'` (using the actual carriage return character) works.

My hope is that I will one day be able to use rclone to copy files that have control characters in them, at least using a flag like the proposed `--local-no-skip-control-chars`.

**Comment by ncw** [comment]
The support for this is merged now in the latest beta and will be out in 1.50.  It is too big a change for a point release.

**Comment by ncw** [comment]
I've merged the fix for this to master now which means it is in [the latest beta](https://beta.rclone.org) and will be released in v1.50
