### ISSUE TITLE
drive: rclone --dry-run will say it has to make (empty) directories that already exist

### ISSUE THREAD

**Issue by aldones** [rclone/rclone#2800]
#### What is the problem you are having with rclone?
Empty directories are being correctly copied for some time now. With v1.45, --dry-run stopped creating these directories, correctly.
However, since v1.45, it will say "Not making directory as dry run is set" for directories that already exist in the destination.

#### What is your rclone version (output from `rclone version`)
v1.45

Haven't tried the github version because nothing on the log indicated any related change

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bits

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v --dry-run --track-renames sync drive:dir1 drive2:dir2

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
(the following log was edited to remove lots and lots of file references and make it more readable)

2018/11/28 17:48:24 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "-vv" "--dry-run" "--track-renames" "sync" "drive1:dir1" "drive2:/dir1"]
2018/11/28 17:48:24 DEBUG : Using config file from "/root/.rclone.conf"
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file1.pdf: Size and modification time the same (differ by 0s, within tolerance 1ms)
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file1.pdf: Unchanged skipping
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file2.pdf: Size and modification time the same (differ by 0s, within tolerance 1ms)
2018/11/28 17:48:27 DEBUG : CRONOGRAMA/file2.pdf: Unchanged skipping
2018/11/28 17:48:27 DEBUG : pacer: Rate limited, sleeping for 1.816067251s (1 consecutive low level retries)
2018/11/28 17:48:27 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=202264815644, userRateLimitExceeded)
2018/11/28 17:48:27 DEBUG : pacer: Rate limited, sleeping for 2.56224649s (2 consecutive low level retries)
2018/11/28 17:48:27 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=202264815644, userRateLimitExceeded)
2018/11/28 17:48:27 DEBUG : pacer: Resetting sleep to minimum 10ms on success
(... several entries removed ...)
( "- UPDATE ON 11／27" wasn't mentioned on any of the removed lines )
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Finished making map for --track-renames
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for checks to finish
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for renames to finish
2018/11/28 17:48:31 INFO  : Google drive root '/dir1': Waiting for transfers to finish
2018/11/28 17:48:31 NOTICE: - UPDATE ON 11／27: Not making directory as dry run is set
2018/11/28 17:48:31 DEBUG : Google drive root '/dir1': copied 1 directories
2018/11/28 17:48:31 INFO  : Waiting for deletions to finish
2018/11/28 17:48:31 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:               112 / 112, 100%
Transferred:            0 / 0, -
Elapsed time:        6.5s

2018/11/28 17:48:31 DEBUG : 35 go routines active
2018/11/28 17:48:31 DEBUG : rclone: Version "v1.45" finishing with parameters ["rclone" "-vv" "--dry-run" "--track-renames" "sync" "drive1:dir1" "drive2:/dir1"]

**Comment by aldones** [comment]
Issue still exists in 1.46.

**Comment by ishuah** [comment]
This should be fixed in 1b52f8d2a5f95905e3ce9b6e843e6242cae8683c

**Comment by aldones** [comment]
> This should be fixed in [1b52f8d](https://github.com/ncw/rclone/commit/1b52f8d2a5f95905e3ce9b6e843e6242cae8683c)

Will test and report back.

**Comment by aldones** [comment]
> This should be fixed in [1b52f8d](https://github.com/ncw/rclone/commit/1b52f8d2a5f95905e3ce9b6e843e6242cae8683c)

The problem persists. Removing the --create-empty-src-dirs doesn't fix the problem, since it won't ever create empty dirs (which I need, since they indicate that an operation was executed before).

The new test was performed with this new flag added, and resulted on the same behavior as before.

**Comment by ishuah** [comment]
@aldones sorry, I didn't understand the issue at first. 

The expected behavior is for rclone dry run sync to ignore empty directories that already exist on the destination.

Thank you for the clarification, I'll try to this as soon as possible.

**Comment by aldones** [comment]
> @aldones sorry, I didn't understand the issue at first.
> 
> The expected behavior is for rclone dry run sync to ignore empty directories that already exist on the destination.
> 
> Thank you for the clarification, I'll try to this as soon as possible.

Something that might be related, or might be a completely different issue, is that when you rename a directory, instead of renaming the directory on the destination, rclone will create a new directory with the new name, move the files to the new directory, and remove the old one. This is for google drive only, as far as I can tell.

Looks like rclone is doing something weird when handling directories. Or maybe the API is weird.

But somehow I've got a feeling that these 2 issues are related.

**Comment by ncw** [comment]
> Something that might be related, or might be a completely different issue, is that when you rename a directory, instead of renaming the directory on the destination, rclone will create a new directory with the new name, move the files to the new directory, and remove the old one. This is for google drive only, as far as I can tell.

What is your command line for this?  Where are you renaming the directory?  You might want to check out the [--track-renames](https://rclone.org/docs/#track-renames) flag

**Comment by aldones** [comment]
> > Something that might be related, or might be a completely different issue, is that when you rename a directory, instead of renaming the directory on the destination, rclone will create a new directory with the new name, move the files to the new directory, and remove the old one. This is for google drive only, as far as I can tell.
> 
> What is your command line for this? Where are you renaming the directory? You might want to check out the [--track-renames](https://rclone.org/docs/#track-renames) flag

I'm using --track-renames. It works, even if in a roundabout way.

My command line is usually something like

rclone -v --track-renames sync --create-empty-src-dirs A:dir1 B:dir2

Nothing fancy.

File renames work perfectly.
Directory renames "work", but instead of simply renaming the directory, rclone creates a new one with the new name, move the files from the old to the new, and then remove the old one. The end effect is mostly the same. The only actual rename is the renaming (server side move) of the files within the directory.

**Comment by ncw** [comment]
> Directory renames "work", but instead of simply renaming the directory, rclone creates a new one with the new name, move the files from the old to the new, and then remove the old one. The end effect is mostly the same. The only actual rename is the renaming (server side move) of the files within the directory.

Ah, I see what you mean.

It would take a lot more logic to detect a directory and everything in it is the same then rename it, so rclone goes for renaming each file individually which is less efficient, but as you said the end effect is the same.

**Comment by lzukw** [comment]
I just wanted to mention, that I have the same issue with a Microsoft Onedrive-remote:

`rclone sync --dry-run --tpslimit=10 --create-empty-src-dirs --log-file=rclone.log --progress remote:00_daten/ /home/zukw/00_daten/`
reports 
`<date time> NOTICE: path/to/emtydirectory: Not making directory as dry run is set`
for each empty directory, alltough these empty directory exists already on source and destination.

Hope, that helps a little bit.
