### ISSUE TITLE
Serve DLNA not working on Samsung TV

### ISSUE THREAD

**Issue by agncr** [rclone/rclone#3253]
#### What is the problem you are having with rclone?
TV shows no playable content from DLNA share. I can see it under sources, but after choosing it, it tells me "the content cannot be displayed"

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0-115-g2c72e7f0-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 9, 64 Bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve dlna remote:Media

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone -vvv serve dlna gcrypt:Media/Movies                     
2019/06/11 10:39:59 DEBUG : rclone: Version "v1.47.0-115-g2c72e7f0-beta" starting with parameters ["rclone" "-vvv" "serve" "dlna" "remote:Media/"]
Enter configuration password:                               
password:
2019/06/11 10:40:04 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/06/11 10:40:07 DEBUG : Adding path "vfs/forget" to remote control registry
2019/06/11 10:40:07 DEBUG : Adding path "vfs/refresh" to remote control registry  
2019/06/11 10:40:07 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/06/11 10:40:07 NOTICE: Encrypted drive 'remote:Media/': Serving HTTP on [::]:7879
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on lo
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on vethecf93a0               
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on br-ff002a7d26fd                
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on docker0                        
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on br-7929a085d1c8                 
2019/06/11 10:40:07 INFO  : DLNA server on :7879: Started SSDP on enp3s0                                    
2019/06/11 10:40:13 INFO  : /ctl: 192.168.178.57:53172 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:17 INFO  : /ctl: 192.168.178.57:53173 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:17 INFO  : /ctl: 192.168.178.57:53174 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:21 INFO  : /ctl: 192.168.178.57:53175 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
2019/06/11 10:40:21 INFO  : /ctl: 192.168.178.57:53176 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)

Every time i clicked on refresh (in the tv), i got 2 of these POST 200 messages.

To check, that the share is working properly i also tested it with VLC on my Android device and got it working. So the combination of rclone-dlna and my Samsung is not working at the moment.

**Comment by ncw** [comment]
I see you are running it in a docker container... I'm not 100% sure that will work unless you bridge the networking to the outside world.

Can you try it not in a docker container?

Any thoughts on this @sretlawd ?

**Comment by agncr** [comment]
I'm not running it in a docker container. Just the latest binary on the host. But i have docker installed on my machine.
I think it's starting the dlna server on all interfaces (enp3s0 is my main interface), wherefore it's also started on the interface docker0.

**Comment by ncw** [comment]
> I'm not running it in a docker container. Just the latest binary on the host. But i have docker installed on my machine.
> I think it's starting the dlna server on all interfaces (enp3s0 is my main interface), wherefore it's also started on the interface docker0.

Sorry, jumped to conclusions there!

I think we'll have to wait for  @sretlawd to weigh in!

**Comment by sretlawd** [comment]
Hmm, do you know what series / year is your Samsung (mine's an F series)?  Might be worth adding a --log-trace to get all the traffic being sent, too, though there'll be a lot of it.

Would also be interesting to know if a super simple config works or not - just a local directory with a one or two media files.  Personally I havn't even tried using subdirectories, filenames with weird characters, etc.  (But don't know of any reason it wouldn't work, either!)

And just to double check - you're getting "the content cannot be displayed" while browsing, where you expect to see a list of files?  You havn't gotten as far as trying to play something back?

**Comment by agncr** [comment]
I have a Samsung UE55MU6199. It's from late 2017. There is no option like --log-trace. Did you mean to add a new command?

I've checked with an absolute folder: one mkv-file, a few subtitles and a few fanarts. But i'm also getting not playable.

My root folder contains a lot of folders with movies in it. I thought it would either display me those folders (like in VLC on Android) or the files.

**Comment by sretlawd** [comment]
Definitely a couple years newer than mine, then - must be something in the Content Directory XML output that it doesn't like?  I havn't looked at that at all yet, but I'll compare it with minidlna and see if anything jumps out at me.

There's a --log-trace on the dlna subcommand -  `rclone -vv serve dlna remote:Media --log-trace`.  That said, what's being output at that point is pretty static, so don't expect it to help much.

Indeed, it should definitely be displaying the file listing at that point, just wanted to make it wasn't an unsupported codec issue, since I get the same error when trying to play h265 on my older TV.  :-)

**Comment by agncr** [comment]
Tested yesterday with anacrolix/dms directly. But with it i get a "no content found". VLC on Android works there too.

**Comment by Bal11254** [comment]
2019/07/26 16:31:10 DEBUG : DLNA server on :4455: unrecognized file type: ************.mkv

Cannot listen videos, mkv avi, mp3
Only photos.

**Comment by ncw** [comment]
@Bal11254 we finally worked out why you only get photos - it is because the mime types on your system aren't working...  This should be fixed in #3475 - can you try the beta there?

What system are you using?

**Comment by mt025** [comment]
I'm having the same issue with DLNA not working on my Samsung TV. In my case, it just says 'Loading...' forever. Working fine in VLC and used the same TV before on MiniDLNA.

T32E390SX (2016)

I will have a look further to see if I can spot any reason why this is happening.

<details>
<summary>Picture</summary>
<img src='https://user-images.githubusercontent.com/2631330/63594908-974f0e00-c5af-11e9-92b8-84229e3214f1.png'/>
</details>

**Log with `-vv --log-trace`**

```
2019/08/23 12:58:27 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "-vv" "-L" "serve" "dlna" "/data/data/com.termux/files/home/_External" "--read-only" "--log-trace"]
2019/08/23 12:58:27 NOTICE: Config file "/data/data/com.termux/files/home/.config/rclone/rclone.conf" not found - using defaults
2019/08/23 12:58:27 INFO  : Local file system at /data/data/com.termux/files/home/_External: poll-interval is not supported by this remote
2019/08/23 12:58:27 DEBUG : Adding path "vfs/forget" to remote control registry
2019/08/23 12:58:27 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/08/23 12:58:27 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/08/23 12:58:27 NOTICE: Local file system at /data/data/com.termux/files/home/_External: Serving HTTP on [::]:7879
2019/08/23 12:58:27 INFO  : DLNA server on :7879: Started SSDP on p2p0
2019/08/23 12:58:27 INFO  : DLNA server on :7879: Started SSDP on lo
2019/08/23 12:58:27 INFO  : DLNA server on :7879: Started SSDP on wlan0
2019/08/23 12:59:07 DEBUG : GET /rootDesc.xml HTTP/1.1
Host: 192.168.0.43:7879
Accept-Language: en-us
Connection: Keep-Alive
Content-Length: 0
User-Agent: DLNADOC/1.50 SEC_HHP_[TV] LT48E390S-JC/1.0 UPnP/1.0

2019/08/23 12:59:07 DEBUG : HTTP/1.1 200 OK
Content-Length: 2535
Cache-Control: private, max-age=60
Content-Type: text/xml; charset="utf-8"

<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0"
      xmlns:dlna="urn:schemas-dlna-org:device-1-0"
      xmlns:sec="http://www.sec.co.kr/dlna">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
    <friendlyName>rclone (localhost)</friendlyName>
    <manufacturer>rclone (rclone.org)</manufacturer>
    <manufacturerURL>https://rclone.org/</manufacturerURL>
    <modelDescription>rclone</modelDescription>
    <modelName>rclone</modelName>
    <modelNumber>v1.48.0</modelNumber>
    <modelURL>https://rclone.org/</modelURL>
    <serialNumber>00000000</serialNumber>
    <UDN>uuid:38d203ea-1f94-d996-dbf9-e1990c28eb9e</UDN>
    <dlna:X_DLNACAP/>
    <dlna:X_DLNADOC>DMS-1.50</dlna:X_DLNADOC>
    <dlna:X_DLNADOC>M-DMS-1.50</dlna:X_DLNADOC>
    <sec:ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:ProductCap>
    <sec:X_ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:X_ProductCap>
    <iconList>
      <icon>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>8</depth>
        <url>/static/rclone-48x48.png</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>8</depth>
        <url>/static/rclone-120x120.png</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
        <SCPDURL>/static/ContentDirectory.xml</SCPDURL>
        <controlURL>/ctl</controlURL>
        <eventSubURL></eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
        <SCPDURL>/static/ConnectionManager.xml</SCPDURL>
        <controlURL>/ctl</controlURL>
        <eventSubURL></eventSubURL>
      </service>
      <service>
        <serviceType>urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1</serviceType>
        <serviceId>urn:microsoft.com:serviceId:X_MS_MediaReceiverRegistrar</serviceId>
        <SCPDURL>/static/X_MS_MediaReceiverRegistrar.xml</SCPDURL>
        <controlURL>/ctl</controlURL>
        <eventSubURL></eventSubURL>
      </service>
    </serviceList>
    <presentationURL>/</presentationURL>
  </device>
</root>
2019/08/23 12:59:07 INFO  : /rootDesc.xml: 192.168.0.12:54835 GET 200  %!s(<nil>)
2019/08/23 12:59:07 INFO  : /static/X_MS_MediaReceiverRegistrar.xml: 192.168.0.12:54838 GET 200  %!s(<nil>)
2019/08/23 12:59:07 INFO  : /static/ContentDirectory.xml: 192.168.0.12:54836 GET 200  %!s(<nil>)
2019/08/23 12:59:07 INFO  : /static/ConnectionManager.xml: 192.168.0.12:54837 GET 200  %!s(<nil>)
2019/08/23 12:59:07 DEBUG : POST /ctl HTTP/1.1
Host: 192.168.0.43:7879
Connection: close
Accept: */*
Connection: close
Content-Length: 313
Content-Type: text/xml; charset="utf-8"
Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#GetSearchCapabilities"
User-Agent: DLNADOC/1.50 SEC_HHP_[TV] LT48E390S-JC/1.0 UPnP/1.0

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Body>
<u:GetSearchCapabilities xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
</u:GetSearchCapabilities>
</s:Body>
</s:Envelope>
2019/08/23 12:59:07 DEBUG : HTTP/1.1 200 OK
Connection: close
Content-Type: text/xml; charset="utf-8"
Ext:

<?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetSearchCapabilitiesResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><SearchCaps></SearchCaps></u:GetSearchCapabilitiesResponse></s:Body></s:Envelope>
2019/08/23 12:59:07 INFO  : /ctl: 192.168.0.12:54839 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#GetSearchCapabilities" %!s(<nil>)
2019/08/23 12:59:08 INFO  : /static/rclone-120x120.png: 192.168.0.12:54840 GET 200  %!s(<nil>)
2019/08/23 12:59:20 DEBUG : POST /ctl HTTP/1.1
Host: 192.168.0.43:7879
Connection: close
Accept: */*
Connection: close
Content-Length: 445
Content-Type: text/xml; charset="utf-8"
Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
User-Agent: DLNADOC/1.50 SEC_HHP_[TV] LT48E390S-JC/1.0 UPnP/1.0

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>0</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse></s:Body></s:Envelope>
2019/08/23 12:59:20 DEBUG : HTTP/1.1 200 OK
Connection: close
Content-Type: text/xml; charset="utf-8"
Ext:

<?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;DIDL-Lite xmlns:dc=&#34;http://purl.org/dc/elements/1.1/&#34; xmlns:upnp=&#34;urn:schemas-upnp-org:metadata-1-0/upnp/&#34; xmlns=&#34;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&#34; xmlns:dlna=&#34;urn:schemas-dlna-org:metadata-1-0/&#34;&gt;&lt;object&gt;&lt;Path&gt;/&lt;/Path&gt;&lt;/object&gt;&lt;/DIDL-Lite&gt;</Result></u:BrowseResponse></s:Body></s:Envelope>
2019/08/23 12:59:20 INFO  : /ctl: 192.168.0.12:54904 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
```

**Comment by sretlawd** [comment]
@mt025 Thanks for the log, I think the PR I just submitted might do the trick.

My Samsung TV starts out with a "BrowseDirectChildren" on the root, but it looks like yours is starting out with a "BrowseMetadata", and the response we were sending out to that was completely wrong, so I can understand why the TV would just hang.  Hope it works or at least makes a bit more progress, let us know.

**Comment by ncw** [comment]
I've merged @sretlawd 's fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50

Thank you @sretlawd :-)

**Comment by mt025** [comment]
I'll give it a test when its up @ncw, was having trouble building as I'm not very familiar with go.

**Comment by mt025** [comment]
@sretlawd @ncw this is definitely a step in the right direction, as the TV no longer hangs at the loading screen, however I still get 'no content found'.

Here is a new log

```
2019/09/15 16:58:21 DEBUG : rclone: Version "v1.49.0-064-g8c038326-beta" starting with parameters ["./rclone-v1.49.0-064-g8c038326-beta-linux-amd64/rclone" "-vv" "-L" "serve" "dlna" "." "--log-trace"]
2019/09/15 16:58:21 NOTICE: Config file "/home/john/.config/rclone/rclone.conf" not found - using defaults
2019/09/15 16:58:21 INFO  : Local file system at /home/john: poll-interval is not supported by this remote
2019/09/15 16:58:21 DEBUG : Adding path "vfs/forget" to remote control registry
2019/09/15 16:58:21 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/09/15 16:58:21 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/09/15 16:58:21 NOTICE: Local file system at /home/john: Serving HTTP on [::]:7879
2019/09/15 16:58:22 INFO  : DLNA server on :7879: Started SSDP on ens32
2019/09/15 16:58:32 DEBUG : POST /ctl HTTP/1.1
Host: 192.168.0.87:7879
Connection: close
Accept: */*
Connection: close
Content-Length: 445
Content-Type: text/xml; charset="utf-8"
Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
User-Agent: DLNADOC/1.50 SEC_HHP_[TV] LT48E390S-JC/1.0 UPnP/1.0

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>0</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse></s:Body></s:Envelope>
2019/09/15 16:58:32 DEBUG : HTTP/1.1 200 OK
Connection: close
Content-Type: text/xml; charset="utf-8"
Ext:

<?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;DIDL-Lite xmlns:dc=&#34;http://purl.org/dc/elements/1.1/&#34; xmlns:upnp=&#34;urn:schemas-upnp-org:metadata-1-0/upnp/&#34; xmlns=&#34;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&#34; xmlns:dlna=&#34;urn:schemas-dlna-org:metadata-1-0/&#34;&gt;&lt;container id=&#34;0&#34; parentID=&#34;-1&#34; restricted=&#34;1&#34; searchable=&#34;0&#34; childCount=&#34;0&#34;&gt;&lt;upnp:class&gt;object.container.storageFolder&lt;/upnp:class&gt;&lt;dc:title&gt;/&lt;/dc:title&gt;&lt;/container&gt;&lt;/DIDL-Lite&gt;</Result></u:BrowseResponse></s:Body></s:Envelope>
2019/09/15 16:58:32 INFO  : /ctl: 192.168.0.12:34692 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" %!s(<nil>)
```

**Comment by sretlawd** [comment]
OK, it looks like the metadata has childCount=0, so most likely need to either set that to the number of contained files, or maybe we can just omit it.  I'll look at what minidlna does and send another change up here in a bit.

**Comment by ilteoood** [comment]
Hi @sretlawd,
there is any news about this?
I've the same problem of @mt025 : "No content found".
I use the beta version on docker, with this compose configuration:

version: '2'
services:
  rclone_dlna:
      image: rclone/rclone:beta
      container_name: rclone_dlna
      restart: always
      command: serve dlna GDrive:/
      network_mode: host
      volumes:
        - /home/pi/rclone/config:/config/rclone
      environment:
        - PHP_TZ=Europe/Rome
        - PUID=1000
        - PGID=1000
      dns:
        - 1.1.1.1

But the problem persist even with the latest stable binary.
No problem with VNC.

**Comment by sretlawd** [comment]
The childCount fix made above solved it, as far as I know, but that error message could have many potential causes...  Can you give it a try using just a local filesystem (instead of GDrive) and just 2-3 media files and see if that works?  If you want, you can run add "-vv —log-trace” to the command and I might be able to spot some things that are happening out of order or wrong.

**Comment by ilteoood** [comment]
Hi @sretlawd,
I've changed my compose as follow:

version: '2'
services:
  rclone_dlna:
      image: rclone/rclone:beta
      container_name: rclone_dlna
      restart: always
      command: serve dlna /config/mount -vv --log-trace
      network_mode: host
      volumes:
        - /home/pi/rclone/config:/config/rclone
        - /home/pi/RS/test:/config/mount
      environment:
        - PHP_TZ=Europe/Rome
        - PUID=1000
        - PGID=1000
      dns:
        - 1.1.1.1

This is the current content of the local folder:
![image](https://user-images.githubusercontent.com/6383527/84158201-e3e6d580-aa6b-11ea-91cc-a237d6f1906d.png)

Even in this case, VLC works but Samsung tv doesn't.

This is the log trace:
      </service>,
      <service>,
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>,
        <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>,
        <SCPDURL>/static/ConnectionManager.xml</SCPDURL>,
        <controlURL>/ctl</controlURL>,
        <eventSubURL></eventSubURL>,
      </service>,
      <service>,
        <serviceType>urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1</serviceType>,
        <serviceId>urn:microsoft.com:serviceId:X_MS_MediaReceiverRegistrar</serviceId>,
        <SCPDURL>/static/X_MS_MediaReceiverRegistrar.xml</SCPDURL>,
        <controlURL>/ctl</controlURL>,
        <eventSubURL></eventSubURL>,
      </service>,
    </serviceList>,
    <presentationURL>/</presentationURL>,
  </device>,
</root>,
2020/06/09 14:20:16 INFO  : /rootDesc.xml: 192.168.1.155:53676 GET 200  ,
2020/06/09 14:20:16 INFO  : /rootDesc.xml: 192.168.1.155:53674 GET 200  ,
2020/06/09 14:20:16 DEBUG : GET /rootDesc.xml HTTP/1.1
,
Host: 192.168.1.128:7879
,
Connection: close
,
Connection: close
,
Date: Tue, 09 Jun 2020 14:20:16 GMT
,
User-Agent: 6.2.9200 2/, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
,

,
2020/06/09 14:20:16 DEBUG : HTTP/1.1 200 OK
,
Content-Length: 2556
,
Cache-Control: private, max-age=60
,
Content-Type: text/xml; charset="utf-8"
,

,
<?xml version="1.0"?>,
<root xmlns="urn:schemas-upnp-org:device-1-0",
      xmlns:dlna="urn:schemas-dlna-org:device-1-0",
      xmlns:sec="http://www.sec.co.kr/dlna">,
  <specVersion>,
    <major>1</major>,
    <minor>0</minor>,
  </specVersion>,
  <device>,
    <deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>,
    <friendlyName>rclone (raspberrypi)</friendlyName>,
    <manufacturer>rclone (rclone.org)</manufacturer>,
    <manufacturerURL>https://rclone.org/</manufacturerURL>,
    <modelDescription>rclone</modelDescription>,
    <modelName>rclone</modelName>,
    <modelNumber>v1.52.0-020-g26fb9007-beta</modelNumber>,
    <modelURL>https://rclone.org/</modelURL>,
    <serialNumber>00000000</serialNumber>,
    <UDN>uuid:79781629-ac0d-6884-aa0e-636e699a28f7</UDN>,
    <dlna:X_DLNACAP/>,
    <dlna:X_DLNADOC>DMS-1.50</dlna:X_DLNADOC>,
    <dlna:X_DLNADOC>M-DMS-1.50</dlna:X_DLNADOC>,
    <sec:ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:ProductCap>,
    <sec:X_ProductCap>smi,DCM10,getMediaInfo.sec,getCaptionInfo.sec</sec:X_ProductCap>,
    <iconList>,
      <icon>,
        <mimetype>image/png</mimetype>,
        <width>48</width>,
        <height>48</height>,
        <depth>8</depth>,
        <url>/static/rclone-48x48.png</url>,
      </icon>,
      <icon>,
        <mimetype>image/png</mimetype>,
        <width>120</width>,
        <height>120</height>,
        <depth>8</depth>,
        <url>/static/rclone-120x120.png</url>,
      </icon>,
    </iconList>,
    <serviceList>,
      <service>,
        <serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>,
        <serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>,
        <SCPDURL>/static/ContentDirectory.xml</SCPDURL>,
        <controlURL>/ctl</controlURL>,
        <eventSubURL></eventSubURL>,
      </service>,
      <service>,
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>,
        <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>,
        <SCPDURL>/static/ConnectionManager.xml</SCPDURL>,
        <controlURL>/ctl</controlURL>,
        <eventSubURL></eventSubURL>,
      </service>,
      <service>,
        <serviceType>urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1</serviceType>,
        <serviceId>urn:microsoft.com:serviceId:X_MS_MediaReceiverRegistrar</serviceId>,
        <SCPDURL>/static/X_MS_MediaReceiverRegistrar.xml</SCPDURL>,
        <controlURL>/ctl</controlURL>,
        <eventSubURL></eventSubURL>,
      </service>,
    </serviceList>,
    <presentationURL>/</presentationURL>,
  </device>,
</root>,
2020/06/09 14:20:16 INFO  : /rootDesc.xml: 192.168.1.155:53673 GET 200  ,
