### ISSUE TITLE
FTP:  multi thread copies hang when server is pure-ftpd

### ISSUE THREAD

**Issue by berniegp** [rclone/rclone#3445]
#### What is the problem you are having with rclone?
rclone hangs when copying from an ftp remote to a local directory.

I can see the transfer rate steadily doing down and the ETA going up. No bytes are transferred after the reported error and the command must be killed with ^C.

It looks like rclone is choking on status messages from the ftp server (3.969 seconds (measured here), 63.77 Mbytes per second).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.48.0-191-g712f7e38-beta
- os/arch: linux/amd64
- go version: go1.12.8
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu server 18.04LTS 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
FTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy ftp_backup:borg /srv/backups/data/backup-repo --progress

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/08/15 08:34:15 DEBUG : rclone: Version "v1.48.0-191-g712f7e38-beta" starting with parameters ["rclone" "copy" "ftp_backup:borg" "/srv/backups/data/back]
2019/08/15 08:34:15 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/08/15 08:34:15 DEBUG : ftp://ftp.redacted.net:21/borg: Connecting to FTP server
2019-08-15 08:34:15 INFO  : README: Copied (new)
2019-08-15 08:34:15 INFO  : hints.156: Copied (new)
2019-08-15 08:34:15 INFO  : config: Copied (new)
2019-08-15 08:34:15 INFO  : index.156: Copied (new)
2019-08-15 08:34:15 INFO  : integrity.156: Copied (new)
2019-08-15 08:34:15 INFO  : lock.roster: Copied (new)
2019-08-15 08:34:15 INFO  : nonce: Copied (new)
2019-08-15 08:34:15 INFO  : lock.exclusive/redacted.server.com@181140264486654.30488-0: Copied (new)
2019-08-15 08:34:15 INFO  : Local file system at /srv/backups/data/backup-repo: Waiting for checks to finish
2019-08-15 08:34:15 INFO  : Local file system at /srv/backups/data/backup-repo: Waiting for transfers to finish
2019-08-15 08:34:15 INFO  : data/0/1: Copied (new)
2019-08-15 08:34:15 DEBUG : data/0/100: Starting multi-thread copy with 2 parts of size 250.500M
2019-08-15 08:34:15 DEBUG : data/0/10: Starting multi-thread copy with 2 parts of size 251.188M
2019-08-15 08:34:15 DEBUG : data/0/101: Starting multi-thread copy with 2 parts of size 250.125M
2019-08-15 08:34:15 DEBUG : data/0/102: Starting multi-thread copy with 2 parts of size 250.125M
2019-08-15 08:34:15 DEBUG : data/0/100: multi-thread copy: stream 1/2 (0-262668288) size 250.500M starting
2019-08-15 08:34:15 DEBUG : data/0/100: multi-thread copy: stream 2/2 (262668288-525279867) size 250.446M starting
2019-08-15 08:34:15 DEBUG : data/0/10: multi-thread copy: stream 1/2 (0-263389184) size 251.188M starting
2019-08-15 08:34:15 DEBUG : data/0/10: multi-thread copy: stream 2/2 (263389184-526659407) size 251.074M starting
2019-08-15 08:34:15 DEBUG : data/0/101: multi-thread copy: stream 1/2 (0-262275072) size 250.125M starting
2019-08-15 08:34:15 DEBUG : data/0/101: multi-thread copy: stream 2/2 (262275072-524447128) size 250.027M starting
2019-08-15 08:34:15 DEBUG : data/0/102: multi-thread copy: stream 1/2 (0-262275072) size 250.125M starting
2019-08-15 08:34:15 DEBUG : data/0/102: multi-thread copy: stream 2/2 (262275072-524446376) size 250.026M starting
2019-08-15 08:34:19 DEBUG : data/0/100: multi-thread copy: stream 1/2 (0-262668288) size 250.500M finished
2019-08-15 08:34:19 DEBUG : data/0/100: multi-thread copy: stream 1/2 failed: 150 3.969 seconds (measured here), 63.77 Mbytes per second
Transferred:      253.002M / 59.451 GBytes, 0%, 6.529 MBytes/s, ETA 2h34m44s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            9 / 152, 6%
Elapsed time:       38.7s
Transferring:
 *                                     data/0/10:  0% /502.262M, 0/s, -
 *                                    data/0/100: 50% /500.946M, 12.900M/s, 19s
 *                                    data/0/101:  0% /500.152M, 0/s, -
 *                                    data/0/102:  0% /500.151M, 0/s, -
```

#### Remote config
```
[ftp_backup]
type = ftp
host = ftp.redacted.net
user = user.redacted
pass = password.redacted
concurrency = 1
```

#### Appendix
This is what I get from an ftp session downloading a file
```
$ ftp ftp.redacted.net
Connected to ftp.redacted.net.
220-#########################################
220-#                                       #
220-#  Welcome on ftp.redacted.net          #
220-#########################################
220 This is a private system - No anonymous login
Name (ftp.redacted.net:user): user.redacted
331 User user.redacted OK. Password required
Password:
230-OK. Current directory is /
230 79949946 Kbytes used (15%) - authorized: 524185600 Kb
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> cd borg/data/0
250 OK. Current directory is /borg/data/0
ftp> get 100
local: 100 remote: 100
200 PORT command successful
150-Connecting to port 43755
150 512968.6 kbytes to download
226-File successfully transferred
226 4.705 seconds (measured here), 106.48 Mbytes per second
525279867 bytes received in 4.72 secs (106.2328 MB/s)
```

**Comment by ncw** [comment]
Hmm...

Can you try turning off multi thread copy with `--multi-thread-streams 0`?

Do you know which FTP server this is? As in what version of software?

It might be worth getting wireshark out to see if you can see what is happening?

A status messages as an error generally indicates rclone and the server have got out of sync somehow.

**Comment by berniegp** [comment]
`--multi-thread-streams 0` seems to remove the problem (transferred 60GB successfully)

I also tested `--multi-thread-streams 0` with `concurrency = 3` since I'm allowed 3 simultaneous connections on that FTP server and it works as well.

After a successful copy, I tried again without `--multi-thread-streams 0` and it worked *as long as there were no files to download* (i.e. no differences). I got the "hanging" again over the 3 connections if forced a redownload of some files by deleting them on the destination.

I don't control the FTP server so unfortunately I most likely can't give all its details. Here's what I found:
```
ftp> rhelp
---> HELP
214-The following SITE commands are recognized
 ALIAS
 CHMOD
 IDLE
 UTIME
214 Pure-FTPd - http://pureftpd.org/
ftp> status
Connected to ftp.redacted.net.
No proxy connection.
Connecting using address family: any.
Mode: stream; Type: binary; Form: non-print; Structure: file
Verbose: on; Bell: off; Prompting: on; Globbing: on
Store unique: off; Receive unique: off
Case: off; CR stripping: on
Quote control characters: on
Ntrans: off
Nmap: off
Hash mark printing: off; Use of PORT cmds: on
Tick counter printing: off
```

So I guess it's Pure-FTPd as the server. If more info is required, I could always open a ticket with the hosting provider asking for the actual version.

**Comment by berniegp** [comment]
I was able to reproduce the issue in a VM running Ubuntu server 18.04LTS.

This is the ftp server package I used:
`pure-ftpd/bionic,now 1.0.46-1build1 amd64 [installed]`

So I can reproduce this issue by connecting to localhost pure-ftpd server to the the `rclone copy`

**Comment by berniegp** [comment]
Note that from local dir to ftp does not exhibit the same problem in my tests.

**Comment by ncw** [comment]
> `--multi-thread-streams 0` seems to remove the problem (transferred 60GB successfully)

Good, at least we have a work-around :-)

> After a successful copy, I tried again without `--multi-thread-streams 0` and it worked _as long as there were no files to download_ (i.e. no differences). I got the "hanging" again over the 3 connections if forced a redownload of some files by deleting them on the destination.

So it sounds like a definite problem with the multi thread download and the FTP backend.

Thanks for your instructions on how to replicate - I manged to replicate them locally here too.

This seems to be dependent on the size of the file transferred.

I do a multithread copy from pureftp in the integration tests, but it never fails... The file transferred is only 128k though.  If I bump that up to 10M then I can see it failing

I see this with wireshark.  Note these two packets are
- sequential
- on the same tcp connection

Note the `150-` message then the `150 ` message which indicates end of message.  This is followed by another `150 ` message in the next frame which isn't allowed.

So I think this is a bug in pureftpd, specifically due to its handling of RETR (which is what multi thread downloads use).

It turns out there is an issue open for this already: https://github.com/jedisct1/pure-ftpd/issues/138

In the capture for the successful test the `measured here` messages comes correctly in the 226 message.

```
Frame 90: 128 bytes on wire (1024 bits), 128 bytes captured (1024 bits)
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 21, Dst Port: 48416, Seq: 742, Ack: 125, Len: 62
File Transfer Protocol (FTP)
    150-Accepted data connection\r\n
        Response code: File status okay; about to open data connection (150)
        Response arg: Accepted data connection
    150 32768.0 kbytes to download\r\n
[Current working directory: ]
```

```
Frame 91: 128 bytes on wire (1024 bits), 128 bytes captured (1024 bits)
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 21, Dst Port: 48416, Seq: 804, Ack: 125, Len: 62
File Transfer Protocol (FTP)
    150 0.014 seconds (measured here), 1665.27 Mbytes per second\r\n
        Response code: File status okay; about to open data connection (150)
        Response arg: 0.014 seconds (measured here), 1665.27 Mbytes per second
[Current working directory: ]
```

**Comment by berniegp** [comment]
Good catch! That motivated me to do some "light" reading of the FTP RFC to understand those multi-line replies. :)

Not sure what you can do on your end then. I'm curious to know how Filezilla or lftp handle such an invalid response from the server though.

**Comment by ncw** [comment]
The problem is triggered by the multi thread downloads. I imagine that FileZilla and lftp don't do those by default.

**Comment by berniegp** [comment]
It seems that https://github.com/jedisct1/pure-ftpd/ nuked all their issues. I can't find any issue tracker on the official website; only a commercial support offer (https://www.pureftpd.org/project/pure-ftpd/support/)

Not sure how to track this one now!

**Comment by ncw** [comment]
> It seems that https://github.com/jedisct1/pure-ftpd/ nuked all their issues. I can't find any issue tracker on the official website; only a commercial support offer (https://www.pureftpd.org/project/pure-ftpd/support/)

Yes I noticed that a while back :-(
 
> Not sure how to track this one now!

I contacted the author on twitter and his reply was "send a patch".  So that is always an option!

**Comment by ncw** [comment]
I have attempted to make a workaround in rclone for this - testing appreciated!

https://beta.rclone.org/branch/v1.51.0-065-gaa9c5858-fix-3445-pureftp-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by berniegp** [comment]
I tested your beta version and confirmed that my local VM test now works. Before doing that I also confirmed that the latest release still fails with the test scenario.

I can't really test it on the production server at this time, but I think you have that covered in #3984 anyway!

**Comment by berniegp** [comment]
Thanks for your help!

**Comment by ncw** [comment]
Thanks for testing @berniegp - much appreciated.
