### ISSUE TITLE
rclone Cannot Update Hidden Files On Windows

### ISSUE THREAD

**Issue by iseahound** [rclone/rclone#3839]
If I have "Folder 1" and "Folder 2", and there is a hidden file in each of the folders rclone will throw the error

> ERROR : A.txt: Failed to copy: Access is denied.

To recreate this:

1. Make "Folder 1" and "Folder 2".
2. Create a text file "A.txt" in both folders. 
3. Mark both copies of "A.txt" as hidden. (Right click > Properties > hidden. Or "attrib +h")
4. Fill the two copies of A.txt with different words and sentences. 
5. `>` rclone sync "Folder 1" "Folder 2"

>`>`rclone sync "Folder 1" "Folder 2"
2020/01/01 00:05:57 ERROR : A.txt: Failed to copy: Access is denied.
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting files as there were IO errors
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting directories as there were IO errors
2020/01/01 00:05:57 ERROR : Attempt 1/3 failed with 3 errors and: Access is denied.
2020/01/01 00:05:57 ERROR : A.txt: Failed to copy: Access is denied.
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting files as there were IO errors
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting directories as there were IO errors
2020/01/01 00:05:57 ERROR : Attempt 2/3 failed with 3 errors and: Access is denied.
2020/01/01 00:05:57 ERROR : A.txt: Failed to copy: Access is denied.
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting files as there were IO errors
2020/01/01 00:05:57 ERROR : Local file system at //?/C:/Users/Edison/Desktop/Folder 2: not deleting directories as there were IO errors
2020/01/01 00:05:57 ERROR : Attempt 3/3 failed with 3 errors and: Access is denied.
2020/01/01 00:05:57 Failed to sync with 3 errors: last error was: Access is denied.

This is a really common error in Windows file syncing apps, I'm surprised no one has caught this bug yet!

Happy New Years!

**Comment by ncw** [comment]
Thanks for finding this.

What should rclone be doing here do you think?

Why does rclone get access denied for hidden files?  It can clearly see them in the listing.

I tried this on win 2018 server running as Administrator and it didn't give the error.  Do you think it needs to be running as a user?

**Comment by iseahound** [comment]
I'm running as a user on windows 10. I don't know exactly why windows acts this way, but a simple fix is to unhide the files in the destination folder. "attrib -s -h" should do it. However some users might like their hidden/system file settings to be preserved, so matching the source and destination attributes would be desired. 

I tested in an administrator command prompt and received the same access is denied error. 

Testing using ubuntu on windows works fine. No errors, and files retain their hidden attributes. Weird. 

If someone can confirm the bug I'd appreciate it. (by running as a user on Windows)

**Comment by ncw** [comment]
I managed to replicate this as a Windows 10 user

```
C:\Users\Dev>rclone.exe version
rclone v1.50.2
- os/arch: windows/amd64
- go version: go1.13.4
C:\Users\Dev>mkdir "Folder 1"
C:\Users\Dev>mkdir "Folder 2"
C:\Users\Dev>echo Hello1 > "Folder 1"/A.txt
C:\Users\Dev>echo Hello2 > "Folder 2"/A.txt
C:\Users\Dev>attrib +h "Folder 1"/A.txt
C:\Users\Dev>attrib +h "Folder 2"/A.txt
C:\Users\Dev>rclone.exe sync -vv --retries 1 "Folder 1" "Folder 2"
2020/01/04 17:18:40 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone.exe" "sync" "-vv" "--retries" "1" "Folder 1" "Folder 2"]
2020/01/04 17:18:40 NOTICE: Config file "C:\\Users\\Dev\\.config\\rclone\\rclone.conf" not found - using defaults
2020/01/04 17:18:40 DEBUG : A.txt: Modification times differ by 8.8262432s: 2020-01-04 17:16:50.5713438 +0000 GMT, 2020-01-04 17:16:59.397587 +0000 GMT
2020/01/04 17:18:40 INFO  : Local file system at //?/C:/Users/Dev/Folder 2: Waiting for checks to finish
2020/01/04 17:18:40 DEBUG : A.txt: MD5 = 309df3bcf89ffb2e26b8d821ecdde726 (Local file system at //?/C:/Users/Dev/Folder 1)
2020/01/04 17:18:40 DEBUG : A.txt: MD5 = 4034df3dc687e1162ef6031d5cc2db8a (Local file system at //?/C:/Users/Dev/Folder 2)
2020/01/04 17:18:40 DEBUG : A.txt: MD5 differ
2020/01/04 17:18:40 ERROR : A.txt: Failed to copy: Access is denied.
2020/01/04 17:18:40 INFO  : Local file system at //?/C:/Users/Dev/Folder 2: Waiting for transfers to finish
2020/01/04 17:18:40 ERROR : Local file system at //?/C:/Users/Dev/Folder 2: not deleting files as there were IO errors
2020/01/04 17:18:40 ERROR : Local file system at //?/C:/Users/Dev/Folder 2: not deleting directories as there were IO errors
2020/01/04 17:18:40 ERROR : Attempt 1/1 failed with 3 errors and: Access is denied.
2020/01/04 17:18:40 Failed to sync with 3 errors: last error was: Access is denied.

C:\Users\Dev>
```

This appears to be the root of the problem

```
C:\Users\Dev>echo hellohello > "Folder 1"/A.txt
Access is denied.
```

Updating a hidden file is forbidden.

Here is a description of the problem (for python but I think the problem is the same here)

https://stackoverflow.com/questions/13215716/ioerror-errno-13-permission-denied-when-trying-to-open-hidden-file-in-w-mod

That gave me an idea for fixing it - can you try this?

https://beta.rclone.org/branch/v1.50.2-104-g6ed3179e-fix-3839-win-hidden-beta/ (uploaded in 15-30 mins)

**Comment by iseahound** [comment]
Thanks, that works perfectly.

Looking through the commit answered a few of my questions. Mainly I was confused about how an error that only occurs with CreateFile has anything to do with moving files. I spent a while looking for the FILE_ATTRIBUTE_HIDDEN flag in the windows API in MoveFile &c. before realizing that go abstracts the os operations of file creation/read/write to flags. Your fix solves the problem by bypassing it, and it works well. Much appreciated.

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

**Comment by svivekiyer** [comment]
I am still seeing this excat issue. I had 3 File reporting error and I manually updated 2 via performing unhide and ran rclone and it transffered successfully. 

For 3rd File seeing same error.  I am using rclone version 

[xxxx~]$ rclone --version
rclone v1.62.2
- os/version: centos 7.9.2009 (64 bit)
- os/kernel: 5.15.111.1-rolling-lts(x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none
[xxxx~]$ rclone copy "/smb/xxxx/28xxx13/" "/Volumes/xxxxx/28xxx13/" --progress
.....
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Checks:                48 / 48, 100%
Elapsed time:         4.0s
2023/09/15 04:21:20 Failed to copy: open /Volumes/xxxxx/28xxx13/streaming/28812xxxx310.mp4: permission denied
