### ISSUE TITLE
Add --force-cleanup option to cleanup command

### ISSUE THREAD

**Issue by kennyparsons** [rclone/rclone#3964]
Original forum discussion: https://forum.rclone.org/t/empty-google-drive-trash/14331/5

#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### What problem are you are trying to solve?
The `cleanup` command has some nebulous results, as seen in several of the forum posts. An alternative, more manual command I had great success with was: 
`rclone delete gdrive: --drive-trashed-only --drive-use-trash=false --verbose=2 --fast-list`

This command enumerated and manually deleted several terabytes of junk data sitting the trash, whereas the `cleanup` option was slow and results have varied for many.

#### How do you think rclone should be changed to solve that?

I would like to see an additional flag, such as `--force-cleanup`, available to the `cleanup` command. This flag would essentially be a shortcut to flip the `cleanup` command to a `delete` command with `--drive-trashed-only` and `--drive-use-trash=false` as default attached commands. The `--forced-cleanup` flag ideally would also accept additional, existing flags, such as `--fast-list`, `--verbose=x`, etc.

**Comment by biship** [comment]
Agree. cleanup doesn't seem to clean up everything, or doesn't work as intended.

What's interesting is that I can run empty trash from the GDrive web site and it shows as empty.

This command finds and deletes files that are 3+ months old:
`rclone delete gdrive: --drive-trashed-only --drive-use-trash=false --verbose=2 --fast-list`

**Comment by ncw** [comment]
> The `cleanup` command has some nebulous results, as seen in several of the forum posts.

The cleanup call, calls Googles API to empty the trash which seems a bit nebulous. It sometimes takes days to work.

> An alternative, more manual command I had great success with was: `rclone delete gdrive: --drive-trashed-only --drive-use-trash=false --verbose=2 --fast-list`
> 
> This command enumerated and manually deleted several terabytes of junk data sitting the trash, whereas the `cleanup` option was slow and results have varied for many.

Well, we implemented clean up for Google Team drives with effectively that `rclone delete` command.

I'm pretty sure that running this code for both team drives and non team drives would do the right thing

https://github.com/rclone/rclone/blob/d252816706a3226dbc055616df91f2e1793a0459/backend/drive/drive.go#L2476-L2482

Fancy giving that a go @biship or @kennyparsons ?

**Comment by marciobasel** [comment]
Any chance this gets porperly implemented into rclone?

2025 and emptying a Shared Drive Trash still fails miserably either with native Google tools or with rclone cleanup :-/

Cheers and happy new year to all rclone community and devs!!

**Comment by ncw** [comment]
@marciobasel what errors are you getting? Did you try `--tpslimit 1` to slow `rclone cleanup` down a lot?

**Comment by marciobasel** [comment]
Hey Nick @ncw many thanks. I simply ran "rclone cleanup remote: -vvvv" yesterday and the Trash is still full. The output didn't produce any errors. I am using latest stable rclone btw.

I could give a try to the GO piece of code you posted above but I don't know how I am supposed to run it. Do I have to patch the file manually? Or ... how exactly?

Thanks again.

M

**Comment by ncw** [comment]
@marciobasel 

You can do something like this to delete all the trash

    rclone delete gdrive: --drive-trashed-only --drive-use-trash=false -vv --fast-list

By default rclone calls the google drive API do so it which is very slow.
