### ISSUE TITLE
cloudflare download url error with b2

### ISSUE THREAD

**Issue by roobandev** [rclone/rclone#4477]
#### What is the problem you are having with rclone?
rclone copy through cloudflare url for backblaze is not working

#### What is your rclone version (output from `rclone version`)

rclone-v1.52.2-276-gc2f3949d-beta-linux-amd64

rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux

####  Which cloud storage system are you using? (eg Google Drive)
backblaze b2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv copy bb:BUCKET_NAME/100mb /tmp/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/07/31 15:11:51 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "-vv" "copy" "bb:BUCKET_NAME/100mb" "/tmp/"]
2020/07/31 15:11:52 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/07/31 15:11:54 DEBUG : fs cache: renaming cache item "bb:BUCKET_NAME/100mb" to be canonical "bb:BUCKET_NAME"
2020/07/31 15:11:54 DEBUG : 100mb: Need to transfer - File not found at Destination
2020/07/31 15:11:54 DEBUG : Couldn't decode error response: invalid character 'e' looking for beginning of value
2020/07/31 15:11:54 ERROR : 100mb: Failed to copy: failed to open source object: failed to open for download: Unknown 403 Forbidden (403 unknown)
2020/07/31 15:11:54 ERROR : Fatal error received - not attempting retries
2020/07/31 15:11:54 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (fatal error encountered)
Elapsed time:         0.0s

#### My rclone config
[bb]
type = b2
account = xxxx
key = xxxx
download_url = https://CNAME.DOMAIN.COM/file/BUCKET_NAME/

I am using master key.
I have used all combinations of download_url but none are working and giving the same error.

https://CNAME.DOMAIN.COM/
https://CNAME.DOMAIN.COM/file/
https://CNAME.DOMAIN.COM/file/BUCKET_NAME/

**Comment by animosity22** [comment]
Does it work without cloudflare?

Is there a reason you are using CloudFlare?

I'd surmise it's probably the HTTPS that is breaking it 

If you --dump headers,requests,responses and just run something, that would show it most likely.

**Comment by roobandev** [comment]
Yes it works without cloudflare.
To avoid download cost when using the download url proxied by CF. 
I will do more debugging then.

**Comment by animosity22** [comment]
What's the cost it's avoiding? I'm just curious as I don't use B2.

**Comment by roobandev** [comment]
Outgress costs from b2 is free
https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/

**Comment by roobandev** [comment]
It was working when I tested it back
https://github.com/rclone/rclone/issues/2808

But not sure what changed from b2 end

**Comment by animosity22** [comment]
Ah, thanks! That's why I like to ask as I learn something to.

Since it works without Cloudflare, it's most likely something in CloudFlare.

The piece I'd want to check is the SSL portion.

Are you setup with SSL like this or something different?

![image](https://user-images.githubusercontent.com/5088712/89057622-fb379600-d32b-11ea-8698-af3288e844c2.png)

**Comment by roobandev** [comment]
I have tested with multiple changes
new bucket
new keys
new cname urls
but I keep on seeing reported error. I am not aware of dump command, I will check with that tomorrow

Yes, I made SSL changes in CF. I am able to download a file using the cname url I have created.

**Comment by animosity22** [comment]
and you have the page rules setup?

If you feel that's all good, it be best to run the command and --dump request,headers,bodies

As I guess you don't want to share it here, you can always email ncw and just reference issue number/link in the email.

**Comment by ncw** [comment]
I fixed something to do with this in [the latest beta](https://beta.rclone.org) 957311f4792792125b2e59376edebfb55cd56e21 - can you give that a go?

**Comment by roobandev** [comment]
I will give that a try. Sure

**Comment by roobandev** [comment]
@ncw I gave that a try and still seeing same error. I think the Authorization is causing issue. When i pass the proper auth token in header, i am getting 200 response in postman.

```
2020/08/04 10:37:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/08/04 10:37:12 DEBUG : 100mb: Need to transfer - File not found at Destination
2020/08/04 10:37:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/08/04 10:37:12 DEBUG : HTTP REQUEST (req 0xc000196a00)
2020/08/04 10:37:12 DEBUG : GET /file/BUCKET_NAME/100mb HTTP/1.1
Host: bb.DOMAIN.xyz
User-Agent: rclone/v1.52.2-281-g324077fb-beta
Authorization: XXXX
Accept-Encoding: gzip

2020/08/04 10:37:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/08/04 10:37:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/08/04 10:37:12 DEBUG : HTTP RESPONSE (req 0xc000196a00)
2020/08/04 10:37:12 DEBUG : HTTP/2.0 403 Forbidden
Content-Length: 16
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Ray: 5bd5c0e57a160bed-AMS
Cf-Request-Id: 045976e36c00000bede9340200000001
Content-Type: text/plain; charset=UTF-8
Date: Tue, 04 Aug 2020 05:07:12 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: cloudflare
Set-Cookie: __cfduid=df24ee77c025ac045893433d2882fb94d1596517632; expires=Thu, 03-Sep-20 05:07:12 GMT; path=/; domain=.DOMAIN.xyz; HttpOnly; SameSite=Lax; Secure
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN

```
