### ISSUE TITLE
--max-duration flag is not respected

### ISSUE THREAD

**Issue by blikblum** [rclone/rclone#4504]
#### What is the problem you are having with rclone?
rclone continue to start new transfers even after transfer time limit defined by --max-duration flag is reached.

The test session (log attached) was started at 15:03h and deadline set to 16:03h as per the log: "Transfer session deadline: 2020/08/12 16:03:47".

But even after 16:03h, new transfers are started and completed.

According to log, new sessions were started automatically with new deadlines:
`2020/08/12 16:18:12 INFO  : One drive root 'emuisos/psp': Transfer session deadline: 2020/08/12 17:18:12`
2020/08/12 17:32:36 INFO  : One drive root 'emuisos/psp': Transfer session deadline: 2020/08/12 18:32:36

The session ended only 18:47h apparently due to some errors

#### What is your rclone version (output from `rclone version`)

rclone v1.52.3-298-g770a6f2c-beta
- os/arch: windows/amd64
- go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy -vv --max-duration 1h --log-file log.txt H:\isos\psp OneDrive-luizamericop:emuisos/psp`

Config:
```
[OneDrive-luizamericop]
type = onedrive
token = {"access_token":"xxx"}
drive_id = yyyy
drive_type = personal
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[log.zip](https://github.com/rclone/rclone/files/5066444/log.zip)

**Comment by animosity22** [comment]
Thanks. To slim out the log a bit:

This is when it starts:

```
2020/08/12 15:03:46 DEBUG : rclone: Version "v1.52.3-298-g770a6f2c-beta" starting with parameters ["rclone" "copy" "-vv" "--max-duration" "1h" "--log-file" "log.txt" "H:\\isos\\psp" "OneDrive-luizamericop:emuisos/psp"]
```

So I'd expect at 16:03, no new transfers would go, but:

```
2020/08/12 15:44:12 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 15:45:57 DEBUG : Hero of Sparta.cso: Starting multipart upload
2020/08/12 15:45:58 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 15:47:20 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 15:50:24 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:06:06 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 16:06:08 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 16:06:10 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:06:12 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 16:07:26 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 16:07:28 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 16:07:30 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:07:32 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 16:08:46 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 16:08:48 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 16:08:50 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:08:52 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 16:10:06 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 16:10:08 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 16:10:10 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:10:12 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 16:11:26 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
2020/08/12 16:11:28 DEBUG : Jeanne d'Arc (USA) (PSP) (PSN).zip: Starting multipart upload
2020/08/12 16:11:30 DEBUG : Killzone - Liberation.ISO: Starting multipart upload
2020/08/12 16:11:32 DEBUG : Jeanne Darc USA.iso: Starting multipart upload
2020/08/12 16:12:46 DEBUG : GOD OF WAR BR.iso: Starting multipart upload
```

I just grepped out the starting uploads to make it a bit easier for @ncw to see.

**Comment by Rycochet** [comment]
Just adding that I'm getting this in the official Docker image too (`:latest` tag, so 1.53.2?) -

```
2020/11/23 09:00:00 INFO  : Starting bandwidth limiter at 1MBytes/s
2020/11/23 09:00:00 INFO  : Google drive root '': Transfer session deadline: 2020/11/24 02:00:00
...
2020/11/24 08:47:02 NOTICE:    62.602G / 642.638 GBytes, 10%, 954.972 kBytes/s, ETA 1w8h54m50s (xfr#38958/48970)
```

**Comment by ncw** [comment]
I can replicate this quite easily

    rclone copy --bwlimit 1k -vv --max-duration 10s src src-copy

I can see two things wrong here

- The `context deadline exceeded` errors are being low level retried
    - this isn't too serious and might be difficult to fix as we do want to retry those errors in most cases
    - the retries happen very quickly
- The sync then stops correctly, however rclone then does a high level retry with a new deadline!

```
2020/08/12 15:03:47 INFO  : One drive root 'emuisos/psp': Transfer session deadline: 2020/08/12 16:03:47
2020/08/12 16:18:12 INFO  : One drive root 'emuisos/psp': Transfer session deadline: 2020/08/12 17:18:12
2020/08/12 17:32:36 INFO  : One drive root 'emuisos/psp': Transfer session deadline: 2020/08/12 18:32:36
```

So I think fixing the second problem would be the place to attack this bug.

**Comment by ncw** [comment]
PS as a work-around you can use `--retries 1`.

**Comment by timevortex** [comment]
I had a quick look around at the code and from my naive reading of things, I'm wondering if this fix is as simple as adding WithDeadline to inCtx in sync.go:

```diff --git a/fs/sync/sync.go b/fs/sync/sync.go
index e8ce10ad1..6ac880994 100644
--- a/fs/sync/sync.go
+++ b/fs/sync/sync.go
@@ -149,11 +149,11 @@ func newSyncCopyMove(ctx context.Context, fdst, fsrc fs.Fs, deleteMode fs.Delete
                endTime := time.Now().Add(ci.MaxDuration)
                fs.Infof(s.fdst, "Transfer session deadline: %s", endTime.Format("2006/01/02 15:04:05"))
                s.ctx, s.cancel = context.WithDeadline(ctx, endTime)
+               s.inCtx, s.inCancel = context.WithDeadline(ctx, endTime)
        } else {
                s.ctx, s.cancel = context.WithCancel(ctx)
+               s.inCtx, s.inCancel = context.WithCancel(s.ctx)
        }
-       // Input context - cancel this for graceful stop
-       s.inCtx, s.inCancel = context.WithCancel(s.ctx)
        if s.noTraverse && s.deleteMode != fs.DeleteModeOff {
                fs.Errorf(nil, "Ignoring --no-traverse with sync")
                s.noTraverse = false
```

I don't have experience building go code and testing but if this seems to be on the right track I'll spend time building and testing.

**Comment by timevortex** [comment]
Unfortunately my experiment wasn't successful as making those changes didn't prevent rclone from hanging around over 1h after `--max-timeout` was reached.

**Comment by ncw** [comment]
I've had a go at fixing this if anyone would like to give it a try

[v1.55.0-beta.5261.004fa1c5f.fix-context-deadline](https://beta.rclone.org/branch/fix-context-deadline/v1.55.0-beta.5261.004fa1c5f.fix-context-deadline/) on branch [fix-context-deadline](https://github.com/rclone/rclone/tree/fix-context-deadline) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55

**Comment by blikblum** [comment]
Hi thanks to looking into this.

I still getting the same behavior with rclone 1.55 (on windows),

The difference this time i'm using sync and not copy

Ran rclone with max-duration 9h

At start 31/03 22h, the session deadline was set to 2021/04/01 07:30

When deadline is reached at 7:30,  some uploads are cancelled with "context deadline exceeded" message

There are some errors and everything is started with a new deadline set to 16:30:38

Below relevant parts of the log:

```
2021/03/31 22:30:36 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "sync" "-vv" "--log-file" "log-arcade.txt" "--max-duration" "9h" "--check-first" "--checkers" "4" "--transfers" "2" "F:\\roms\\arcade" "OneDrive-luizamericop:emuroms/arcade"]

2021/03/31 22:30:38 INFO  : One drive root 'emuroms/arcade': Transfer session deadline: 2021/04/01 07:30:38

2021/04/01 07:30:38 DEBUG : mame/fotns.zip: Cancelling multipart upload: Put "https://df.api.onedrive.com/": context deadline exceeded
2021/04/01 07:30:38 DEBUG : mame/funcube4.zip: Cancelling multipart upload: Put "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 DEBUG : pacer: Reducing sleep to 80.180765ms
2021/04/01 07:30:38 NOTICE: mame/fotns.zip: Failed to cancel multipart upload: Delete "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 ERROR : mame/fotns.zip: Failed to copy: Put "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 DEBUG : pacer: Reducing sleep to 60.135573ms
2021/04/01 07:30:38 NOTICE: mame/funcube4.zip: Failed to cancel multipart upload: Delete "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 ERROR : mame/funcube4.zip: Failed to copy: Put "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 ERROR : One drive root 'emuroms/arcade': not deleting files as there were IO errors
2021/04/01 07:30:38 ERROR : One drive root 'emuroms/arcade': not deleting directories as there were IO errors
2021/04/01 07:30:38 ERROR : Attempt 1/3 failed with 17 errors and: Put "https://df.api.onedrive.com/xxxxx context deadline exceeded
2021/04/01 07:30:38 INFO  : One drive root 'emuroms/arcade': Running all checks before starting transfers
2021/04/01 07:30:38 INFO  : One drive root 'emuroms/arcade': Transfer session deadline: 2021/04/01 16:30:38
2021/04/01 07:31:17 DEBUG : pacer: low level retry 1/10 (error Get "https://graph.microsoft.com/v1.0/drives/7cb47be895e02668/items/7CB47BE895E02668!18256/children?$top=1000": EOF)
2021/04/01 07:31:17 DEBUG : pacer: Rate limited, increasing sleep to 120.271146ms
2021/04/01 07:31:38 INFO  : 
Transferred:   	    1.470G / 5.696 GBytes, 26%, 47.766 kBytes/s, ETA 1d1h46m25s
Checks:             17720 / 17720, 100%
Transferred:          315 / 965, 33%
Elapsed time:     9h1m1.4s

2021/04/01 07:32:31 DEBUG : pacer: low level retry 2/10 (error Get "https://graph.microsoft.com/v1.0/drives/7cb47be895e02668/items/7CB47BE895E02668!18256/children?$top=1000": net/http: TLS handshake timeout)
2021/04/01 07:32:31 DEBUG : pacer: Rate limited, increasing sleep to 240.542292ms
2021/04/01 07:32:31 DEBUG : pacer: Reducing sleep to 180.406719ms
2021/04/01 07:32:32 DEBUG : pacer: Reducing sleep to 135.305039ms
2021/04/01 07:32:32 DEBUG : bioses/cpzn1.zip: Size and modification time the same (differ by -321.4722ms, within tolerance 1s)
2021/04/01 07:32:32 DEBUG : bioses/cpzn2.zip: Size and modification time the same (differ by -356.4742ms, within tolerance 1s)
2021/04/01 07:32:32 DEBUG : bioses/cpzn2.zip: Unchanged skipping
2021/04/01 07:32:32 DEBUG : bioses/cpzn1.zip: Unchanged skipping
```

**Comment by ncw** [comment]
I think this may have been fixed by 54771e440218443cae44611660359ee3c5db16d5 which you'll find in [the latest beta](https://beta.rclone.org)
