### ISSUE TITLE
Single-file copy failed with access denied when folder copy succeeds

### ISSUE THREAD

**Issue by guyarad** [rclone/rclone#5271]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/s3-rclone-v-1-52-0-or-after-permission-denied/21961/13

#### What is the problem you are having with rclone?
Inconsistent behavior when using `copy` command for copying a folder as opposed to copying a single file. 
The symptom is that copying a single file fails (but succeeds when copying a folder to the same remote). 
The root-cause is that RCLONE tries to create the remote path (to avoid multiple API calls probably), which means attempting to create a remote *bucket* (a permission that is rarely given when using cloud storage). When that permission isn't given for the user, even if the bucket exists, cloud providers (e.g. S3) will return a "permission denied" error. 

This does not happen when copying a folder, as it seems like RCLONE always tries to list the remote folder prior to trying to copy. So if the bucket exists it will not attempt creating it.

Options to fix raised by @ncw :

1. Avoid creating a bucket altogether, unless `mkdir` is used. This is probably not a good idea as it's backwards incompatible.
2. Listing the remote folder prior to copying a single file. This is also a behavior change, as it adds an API call to single file copy operations (how frequent really is that?). Probably the cleanest option (there's the question of handling list permissions... need to look into that and I'll be happy to help).
3. Using the same existing flow (attempt creating remote path, thus implicitly creating the bucket), but doing something different upon retry (assuming the bucket exist maybe). According to Nick, this is probably more complex. 

Personally, I believe option #2 is the cleanest, both with respect to consistency with the copy behavior when copying a folder, and avoiding unneeded retries.

#### What is your rclone version (output from `rclone version`)
v1.55.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
MacOS Catalina 10.15.7 (but I'm sure this behavior is the same)

#### Which cloud storage system are you using? (e.g. Google Drive)
AWS S3

### The failed command (copying a single file):
```
╰─$ rclone copy -vv bla/bla.txt s3-guy-test:guyarad-test
2021/04/23 21:43:24 DEBUG : Using config file from "/Users/guyarad/.config/rclone/rclone.conf"
2021/04/23 21:43:24 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "copy" "-vv" "bla/bla.txt" "s3-guy-test:guyarad-test"]
2021/04/23 21:43:24 DEBUG : Creating backend with remote "bla/bla.txt"
2021/04/23 21:43:24 DEBUG : fs cache: adding new entry for parent of "bla/bla.txt", "/Users/guyarad/src/bla"
2021/04/23 21:43:24 DEBUG : Creating backend with remote "s3-guy-test:guyarad-test"
2021/04/23 21:43:25 DEBUG : bla.txt: Need to transfer - File not found at Destination
2021/04/23 21:43:25 ERROR : bla.txt: Failed to copy: AccessDenied: Access Denied
	status code: 403, request id: EFK8TVZQ5HQTCH50, host id: j2tCf5VV9A/ChbRSE+eSY4cKsF/V690LMhQzL2VmegXaQVMxVC/31OgJqt95EDu0pbVcETVBJCo=
2021/04/23 21:43:25 ERROR : Attempt 1/3 failed with 1 errors and: AccessDenied: Access Denied
	status code: 403, request id: EFK8TVZQ5HQTCH50, host id: j2tCf5VV9A/ChbRSE+eSY4cKsF/V690LMhQzL2VmegXaQVMxVC/31OgJqt95EDu0pbVcETVBJCo=
... RETRIES OMITTED ...
2021/04/23 21:43:25 INFO  :
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         1.6s

2021/04/23 21:43:25 DEBUG : 6 go routines active
2021/04/23 21:43:25 Failed to copy: AccessDenied: Access Denied
	status code: 403, request id: EFK822P9G8PJKPYF, host id: DvXHGARYgOW/8HFrf9iogUWMxvLxShAhMQ4AlPchDuPwNqweAXeyKPl4UbLDOaOX+IISOUJBENE=
```

### Successful copy with the same remote (copying a folder):
```
╰─$ rclone copy -vv bla/ s3-guy-test:guyarad-test
2021/04/23 21:47:09 DEBUG : Using config file from "/Users/guyarad/.config/rclone/rclone.conf"
2021/04/23 21:47:09 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "copy" "-vv" "bla/" "s3-guy-test:guyarad-test"]
2021/04/23 21:47:09 DEBUG : Creating backend with remote "bla/"
2021/04/23 21:47:09 DEBUG : fs cache: renaming cache item "bla/" to be canonical "/Users/guyarad/src/bla"
2021/04/23 21:47:09 DEBUG : Creating backend with remote "s3-guy-test:guyarad-test"
2021/04/23 21:47:10 DEBUG : S3 bucket guyarad-test: Waiting for checks to finish
2021/04/23 21:47:10 DEBUG : S3 bucket guyarad-test: Waiting for transfers to finish
2021/04/23 21:47:10 DEBUG : bla.txt: MD5 = 3cd7a0db76ff9dca48979e24c39b408c OK
2021/04/23 21:47:10 INFO  : bla.txt: Copied (new)
2021/04/23 21:47:10 INFO  :
Transferred:   	         4 / 4 Bytes, 100%, 12 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.1s

2021/04/23 21:47:10 DEBUG : 6 go routines active
```

### After adding CreateBucket policy to the same user being used
(single-file copy operation succeeds)
```
╰─$ rclone copy -vv bla/bla.txt s3-guy-test:guyarad-test
2021/04/23 21:19:09 DEBUG : Using config file from "/Users/guyarad/.config/rclone/rclone.conf"
2021/04/23 21:19:09 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "copy" "-vv" "bla/bla.txt" 
2021/04/23 21:19:09 DEBUG : Creating backend with remote "bla/bla.txt"
2021/04/23 21:19:09 DEBUG : fs cache: adding new entry for parent of "bla/bla.txt", "/Users/guyarad/src/bla"
2021/04/23 21:19:09 DEBUG : Creating backend with remote "s3-guy-test:guyarad-test"
2021/04/23 21:19:10 DEBUG : bla.txt: Need to transfer - File not found at Destination
2021/04/23 21:19:10 INFO  : S3 bucket guyarad-test: Bucket "guyarad-test" created with ACL "private"
2021/04/23 21:19:11 DEBUG : bla.txt: MD5 = 3cd7a0db76ff9dca48979e24c39b408c OK
2021/04/23 21:19:11 INFO  : bla.txt: Copied (new)
2021/04/23 21:19:11 INFO  :
Transferred:   	         4 / 4 Bytes, 100%, 6 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.4s

2021/04/23 21:19:11 DEBUG : 6 go routines active
```

Thanks guys for the awesome tool!!

**Comment by ncw** [comment]
I think this is worth fixing as it has caused a fair amount of annoyance to users in the past.

> 2\. Listing the remote folder prior to copying a single file. This is also a behavior change, as it adds an API call to single file copy operations (how frequent really is that?). Probably the cleanest option (there's the question of handling list permissions... need to look into that and I'll be happy to help).

Note that we only need to list the root of the bucket once - rclone has a cache of whether the bucket has been created or not so instead of

- make bucket
- copy file

Rclone will do

- list bucket
- if that fails: attempt to make bucket
- copy file

So in the normal case of the bucket already existing it will do no extra API calls compared to current

Most syncs involve listing the bucket anyway - it is possible to do it without but I think most syncs will have list bucket permissions. And there is always `--s3-no-check-bucket` for those difficult to reach edge cases!

**Comment by TyfoidKId** [comment]
fwiw the --s3-no-check-bucket is a good work around but it would nice to not need it. We are trying to create a service with AWS buckets for users and are using the 'principle of least privilege' that AWS recommends.  We also are trying to NOT have user policies but just bucket policies. We also can't have people creating their own buckets (oh they joys of wrapping a service around a service.)
So far this setup has been working the the various clients I'm stress testing (aws cli v2, rclone 1.56, cyberduck) 
   "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:GetObjectTagging",
                "s3:GetObjectVersion",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:RestoreObject",
                "s3:ListBucket"
but I did run into issues until I found the --s3-no-check-bucket switch when trying to just copy one file to an existing bucket. Without that switch it fails straight away but works fine with it 

```
2021/09/24 10:06:37 DEBUG : file-name: Need to transfer - File not found at Destination
2021/09/24 10:06:37 ERROR : file-name: Failed to copy: AccessDenied: Access Denied
```

with it you still get the 
`Need to transfer - File not found at Destination`
error which was throwing me on a large file because rclone was working but it took a few minutes to get started on the large file. Just my 2 cents.  Love rclone, keep up the great work.

**Comment by tooptoop4** [comment]
i am finding in >= 1.60 it no longer prints "Copied (new)" on that 2nd attempt, it just prints "Failed to copy: Forbidden: Forbidden"  from 1st attempt

**Comment by ncw** [comment]
I think this issue is solved with 

      --s3-no-check-bucket     If set, don't attempt to check the bucket exists or create it

**Comment by tooptoop4** [comment]
@ncw  was already using --s3-no-check-bucket so issue still there

**Comment by ncw** [comment]
@tooptoop4 please post a debug log with `-vv --dump headers --low-level-retries 1 --retries 1`

**Comment by tooptoop4** [comment]
@ncw 
```
root@sftp:/# ./rclone-linux-amd64/rclone copy --max-depth 1  mysftp:/redactsftppath/ --include "myfile_2022032206033[0-9].csv" s3:redactbucket/z/zthry2211_2/ --s3-no-check-bucket -vv --dump headers --low-level-retries 1 --retries 1
2022/11/22 06:11:29 DEBUG : rclone: Version "v1.60.1" starting with parameters ["./rclone-linux-amd64/rclone" "copy" "--max-depth" "1" "mysftp:/redactsftppath/" "--include" "myfile_2022032206033[0-9].csv" "s3:redactbucket/z/zthry2211_2/" "--s3-no-check-bucket" "-vv" "--dump" "headers" "--low-level-retries" "1" "--retries" "1"]
2022/11/22 06:11:29 DEBUG : Creating backend with remote "mysftp:/redactsftppath/"
2022/11/22 06:11:29 DEBUG : Using config file from "/rclone-linux-amd64/rclone.conf"
2022/11/22 06:11:29 DEBUG : Setting pass="redact42c" for "mysftp" from environment variable RCLONE_CONFIG_mysftp_PASS
2022/11/22 06:11:29 DEBUG : mysftp: detected overridden config - adding "{Q-pnl}" suffix to name
2022/11/22 06:11:29 DEBUG : Setting pass="redact42c" for "mysftp" from environment variable RCLONE_CONFIG_mysftp_PASS
2022/11/22 06:11:29 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: New connection redactip1:37894->redactip2:22 to "SSH-2.0-OpenSSH_7.4"
2022/11/22 06:11:29 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Shell type "unix" from config
2022/11/22 06:11:30 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Using root directory "/redactsftppath/"
2022/11/22 06:11:30 DEBUG : fs cache: renaming cache item "mysftp:/redactsftppath/" to be canonical "mysftp{Q-pnl}:/redactsftppath/"
2022/11/22 06:11:30 DEBUG : Creating backend with remote "s3:redactbucket/z/zthry2211_2/"
2022/11/22 06:11:30 DEBUG : s3: detected overridden config - adding "{Dn7qA}" suffix to name
2022/11/22 06:11:30 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2022/11/22 06:11:30 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2022/11/22 06:11:30 DEBUG : fs cache: renaming cache item "s3:redactbucket/z/zthry2211_2/" to be canonical "s3{Dn7qA}:redactbucket/z/zthry2211_2"
2022/11/22 06:11:30 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:30 DEBUG : HTTP REQUEST (req 0xc0007de600)
2022/11/22 06:11:30 DEBUG : POST / HTTP/1.1
Host: sts.amazonaws.com
User-Agent: rclone/v1.60.1
Content-Length: 1172
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept-Encoding: gzip

2022/11/22 06:11:30 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:30 DEBUG : myfile_20220125060712.csv: Excluded
2022/11/22 06:11:31 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:31 DEBUG : HTTP RESPONSE (req 0xc0007de600)
2022/11/22 06:11:31 DEBUG : HTTP/1.1 200 OK
Content-Length: 2324
Content-Type: text/xml
Date: Tue, 22 Nov 2022 06:11:31 GMT
X-Amzn-Requestid: redact36c

2022/11/22 06:11:31 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:31 DEBUG : HTTP REQUEST (req 0xc0007de000)
2022/11/22 06:11:31 DEBUG : GET /?delimiter=%2F&encoding-type=url&list-type=2&max-keys=1000&prefix=z%2Fzthry2211_2%2F HTTP/1.1
Host: redactbucket.s3.redactregion.amazonaws.com
User-Agent: rclone/v1.60.1
Authorization: XXXX
X-Amz-Content-Sha256: redact64c
X-Amz-Date: 20221122T061130Z
X-Amz-Security-Token: redactmore1232char
Accept-Encoding: gzip

2022/11/22 06:11:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:31 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:31 DEBUG : HTTP RESPONSE (req 0xc0007de000)
2022/11/22 06:11:31 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 22 Nov 2022 06:11:32 GMT
Server: AmazonS3
X-Amz-Bucket-Region: redactregion
X-Amz-Id-2: redact76c
X-Amz-Request-Id: redact16c

2022/11/22 06:11:31 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:31 DEBUG : S3 bucket redactbucket path z/zthry2211_2: Waiting for checks to finish
2022/11/22 06:11:31 DEBUG : S3 bucket redactbucket path z/zthry2211_2: Waiting for transfers to finish
2022/11/22 06:11:31 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Shell path "/redactsftppath/myfile_20220322060332.csv"
2022/11/22 06:11:31 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Running remote command: md5sum /redactsftppath/myfile_20220322060332.csv
2022/11/22 06:11:31 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Remote command result: redacta32c  /redactsftppath/myfile_20220322060332.csv
2022/11/22 06:11:31 DEBUG : myfile_20220322060332.csv: Parsed hash: redacta32c
2022/11/22 06:11:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:31 DEBUG : HTTP REQUEST (req 0xc0007de300)
2022/11/22 06:11:31 DEBUG : PUT /z/zthry2211_2/myfile_20220322060332.csv HTTP/1.1
Host: redactbucket.s3.redactregion.amazonaws.com
User-Agent: rclone/v1.60.1
Content-Length: 16471500
Authorization: XXXX
Content-Md5: redacta24c
Content-Type: text/csv; charset=utf-8
Expect: 100-Continue
X-Amz-Acl: private
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20221122T061131Z
X-Amz-Meta-Mtime: 1647929398
X-Amz-Security-Token: redactanother1232char
X-Amz-Server-Side-Encryption: AES256
X-Amz-Storage-Class: STANDARD
Accept-Encoding: gzip

2022/11/22 06:11:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:32 DEBUG : HTTP RESPONSE (req 0xc0007de300)
2022/11/22 06:11:32 DEBUG : HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 22 Nov 2022 06:11:32 GMT
Etag: "redacta32c"
Server: AmazonS3
X-Amz-Id-2: redactsome76
X-Amz-Request-Id: redactsome16here
X-Amz-Server-Side-Encryption: AES256
X-Amz-Version-Id: redactsome32here

2022/11/22 06:11:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:32 DEBUG : HTTP REQUEST (req 0xc000878400)
2022/11/22 06:11:32 DEBUG : HEAD /z/zthry2211_2/myfile_20220322060332.csv?versionId=redactsome32here HTTP/1.1
Host: redactbucket.s3.redactregion.amazonaws.com
User-Agent: rclone/v1.60.1
Authorization: XXXX
X-Amz-Content-Sha256: redact64c
X-Amz-Date: 20221122T061132Z
X-Amz-Security-Token: redact1232char

2022/11/22 06:11:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/11/22 06:11:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:32 DEBUG : HTTP RESPONSE (req 0xc000878400)
2022/11/22 06:11:32 DEBUG : HTTP/1.1 403 Forbidden
Connection: close
Content-Type: application/xml
Date: Tue, 22 Nov 2022 06:11:31 GMT
Server: AmazonS3
X-Amz-Id-2: redact76char
X-Amz-Request-Id: redact16char

2022/11/22 06:11:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/11/22 06:11:32 ERROR : myfile_20220322060332.csv: Failed to copy: Forbidden: Forbidden
        status code: 403, request id: redact16char, host id: redact76char
2022/11/22 06:11:32 ERROR : Attempt 1/1 failed with 1 errors and: Forbidden: Forbidden
        status code: 403, request id: redact16char, host id: redact76char
2022/11/22 06:11:32 INFO  :
Transferred:       15.708 MiB / 15.708 MiB, 100%, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         2.6s

2022/11/22 06:11:32 DEBUG : 18 go routines active
2022/11/22 06:11:32 DEBUG : sftp://redactsftpuser@redactsftphost:22//redactsftppath/: Closing 1 unused connections
2022/11/22 06:11:32 Failed to copy: Forbidden: Forbidden
        status code: 403, request id: redact16char, host id: redact76char
root@sftp:/#

```

**Comment by ncw** [comment]
@tooptoop4 - looks like you haven't given rclone permission to HEAD the files to check the upload was OK.

You should find this fixes the problem.

      --s3-no-head          If set, don't HEAD uploaded objects to check integrity

**Comment by tooptoop4** [comment]
do u think https://github.com/rclone/rclone/commit/01877e5a0fc0ccfe36316435bed836845ec78a93 will fix?

**Comment by ncw** [comment]
@tooptoop4 its possible if you have filtered access to versions. Give it a go.

**Comment by tooptoop4** [comment]
confirmed, v1.61 fixes this!

**Comment by ncw** [comment]
Great! I'll close this now.

**Comment by fanlix** [comment]
still exist in v1.61.1
need `--s3-no-check-bucket` to skip error

**Comment by cham423** [comment]
Confirming this behavior in rclone v1.63.1, if the access key is scoped to a specific bucket, you need the `--s3-no-check-bucket` option to be able to upload files.

**Comment by sdarwin** [comment]
still need `--s3-no-check-bucket` to be able to upload a single file.

**Comment by lbadi** [comment]
alternatively you can add` no_check_bucket = true ` directly on the conf file.

**Comment by mrhawkin** [comment]
@ncw This is still an issue in the current release. no_check_bucket = true is a workaround soultion, but I think this issue should be reopened since it is not fixed.
