### ISSUE TITLE
restic cannot connect via tcp/ip unless --stdio option is provided for rclone serve restic

### ISSUE THREAD

**Issue by ElRico** [rclone/rclone#6647]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-v1-61-0-release/34914/3?u=el_rico

#### What is the problem you are having with rclone?

restic cannot connect to rclone via tcp/ip, unless the `--stdio` option is provided for the `rclone serve restic` command.

#### What is your rclone version (output from `rclone version`)

rclone v1.61.0
- os/version: debian 11.6 (64 bit)
- os/kernel: 5.10.0-20-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

debian 11.6 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

Jottacloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
restic stats --verbose -o rclone.args="serve restic --stdio --addr ':9999' --b2-hard-delete -vv"
echo "-------"
restic stats --verbose -o rclone.args="serve restic --addr ':9999' --b2-hard-delete -vv"
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
rclone: 2022/12/21 16:04:30 DEBUG : rclone: Version "v1.61.0" starting with parameters ["rclone" "serve" "restic" "--stdio" "--addr" ":9999" "--b2-hard-delete" "-vv" "<redacted>"]
rclone: 2022/12/21 16:04:30 DEBUG : Creating backend with remote "<redacted>"
rclone: 2022/12/21 16:04:30 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/21 16:04:30 NOTICE: jottacloud root '<redacted>': Serving restic REST API on [http://[::]:9999/]
rclone: 2022/12/21 16:04:30 DEBUG : file-5577006791947779410: GET request error: object not found
rclone: 2022/12/21 16:04:30 DEBUG : keys: list request
repository 46963384 opened (repository version 1) successfully, password is correct
<snip>
-------
rclone: 2022/12/21 16:04:31 DEBUG : rclone: Version "v1.61.0" starting with parameters ["rclone" "serve" "restic" "--addr" ":9999" "--b2-hard-delete" "-vv" "<redacted>"]
rclone: 2022/12/21 16:04:31 DEBUG : Creating backend with remote "<redacted>"
rclone: 2022/12/21 16:04:31 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/21 16:04:32 NOTICE: jottacloud root '<redacted>': Serving restic REST API on [http://[::]:9999/]
rclone: 2022/12/21 16:04:32 INFO  : 
rclone: Transferred:              0 B / 0 B, -, 0 B/s, ETA -
rclone: Elapsed time:         0.4s
rclone: 
rclone: 2022/12/21 16:04:32 DEBUG : 6 go routines active
Fatal: unable to open repository at rclone:jottacloud:<redacted>: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": unexpected EOF
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by darthShadow** [comment]
I think this is already fixed for https://github.com/rclone/rclone/issues/6644

Can you try the binaries from here please: https://beta.rclone.org/branch/fix-6644-serve-restic/v1.62.0-beta.6657.bfd225166.fix-6644-serve-restic/

**Comment by ElRico** [comment]
Unfortunately that build does not fix this issue, but it does yield a different error message. Running the same commands as in the op:

```
rclone: 2022/12/21 16:42:23 DEBUG : rclone: Version "v1.62.0-beta.6657.bfd225166.fix-6644-serve-restic" starting with parameters ["rclone" "serve" "restic" "--stdio" "--addr" ":9999" "--b2-hard-delete" "-vv" "<redacted>"]
rclone: 2022/12/21 16:42:23 DEBUG : Creating backend with remote "<redacted>"
rclone: 2022/12/21 16:42:23 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/21 16:42:24 NOTICE: jottacloud root '<redacted>': Serving restic REST API on [http://[::]:9999/]
rclone: 2022/12/21 16:42:24 DEBUG : file-5577006791947779410: GET request error: object not found
rclone: 2022/12/21 16:42:24 DEBUG : keys: list request
repository 46963384 opened (repository version 1) successfully, password is correct
<snip>
-------
rclone: 2022/12/21 16:42:25 DEBUG : rclone: Version "v1.62.0-beta.6657.bfd225166.fix-6644-serve-restic" starting with parameters ["rclone" "serve" "restic" "--addr" ":9999" "--b2-hard-delete" "-vv" "<redacted>"]
rclone: 2022/12/21 16:42:25 DEBUG : Creating backend with remote "<redacted>"
rclone: 2022/12/21 16:42:25 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/21 16:42:26 NOTICE: jottacloud root '<redacted>': Serving restic REST API on [http://[::]:9999/]
Fatal: unable to open repository at rclone:jottacloud:<redacted>: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by darthShadow** [comment]
That may be due to the duplicate calls to `Serve()` (https://github.com/rclone/rclone/commit/bfd225166f334b31e22298fca18934a31ff1e27b#commitcomment-93820465). 
Will need to wait for ncw to confirm.

**Comment by ncw** [comment]
I think this should fix the problem - can you test please @ElRico 

[v1.62.0-beta.6660.8863fb491.fix-6644-serve-restic](https://beta.rclone.org/branch/fix-6644-serve-restic/v1.62.0-beta.6660.8863fb491.fix-6644-serve-restic/) on branch [fix-6644-serve-restic](https://github.com/rclone/rclone/tree/fix-6644-serve-restic) (uploaded in 15-30 mins)

@darthShadow - Well spotted with the duplicate serve, I've removed that.

**Comment by ElRico** [comment]
Thanks for working on this so quickly @ncw! Alas, I do not have access to my systems for the next seven days. That is why I cannot retest this, or #6646 and #6648 until then.

**Comment by ncw** [comment]
@ElRico - no problems. I'll merge this for v1.61.1 as I'm pretty sure that the fixes are correct, and you can test it there.

**Comment by ncw** [comment]
This fix has been released in v1.61.1 which is available now

**Comment by ElRico** [comment]
@ncw unfortunately this bug does not seem to be fixed with 1.61.1:
```
rclone: 2022/12/29 17:18:33 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "serve" "restic" "--stdio" "--addr" ":9999" "--b2-hard-delete" "-vv" "jottacloud:<redacted>"]
rclone: 2022/12/29 17:18:33 DEBUG : Creating backend with remote "jottacloud:<redacted>"
rclone: 2022/12/29 17:18:33 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/29 17:18:34 DEBUG : file-5577006791947779410: GET request error: object not found
rclone: 2022/12/29 17:18:34 DEBUG : keys: list request
repository 46963384 opened (repository version 1) successfully, password is correct
<snip>
-------
rclone: 2022/12/29 17:18:36 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "serve" "restic" "--addr" ":9999" "--b2-hard-delete" "-vv" "jottacloud:<redacted>"]
rclone: 2022/12/29 17:18:36 DEBUG : Creating backend with remote "jottacloud:<redacted>"
rclone: 2022/12/29 17:18:36 DEBUG : Using config file from "<redacted>"
rclone: 2022/12/29 17:18:36 NOTICE: jottacloud root '<redacted>': Serving restic REST API on [http://[::]:9999/]
Fatal: unable to open repository at rclone:jottacloud:<redacted>: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by ncw** [comment]
> rclone: 2022/12/29 17:18:33 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "serve" "restic" "--stdio" "--addr" ":9999" "--b2-hard-delete" "-vv" "jottacloud:<redacted>"]

Remove the `--stdio` - does it work then?

**Comment by ElRico** [comment]
Sorry, I should have mentioned that I re-ran the test script in the description of this ticket. That runs the command twice, once with `--stdio` and once without. The output is separated by `-------` for readability.
In other words, unfortunately it does not work without `--stdio`.

**Comment by ncw** [comment]
Your second example without `--stdio` seems to be missing the config for restic to talk to port :9999 ? How does that work?

The first example with `--stdio` does work for me.

**Comment by ElRico** [comment]
You are right, I forgot to set the environment variable for the repository with the correct value for test. Thanks for having a look!
