### ISSUE TITLE
Incorrent filename encoding when uploaded from Windows local to sftp (Linux) backend

### ISSUE THREAD

**Issue by sagan** [rclone/rclone#7928]
#### What is the problem you are having with rclone?

Rclone incorrectly encodes (escapes) the filename, when transferring files from local (on Windows) to sftp (on Linux) backend, even with `--local-encoding None` flag set.

See below "Reproduce" section for details.

#### What is your rclone version (output from `rclone version`)

I have tried  latest stable (rclone v1.67.0) and beta (rclone v1.68.0-beta.8049.754e53dbc), the problem can be reproduced in both.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10 & Windows 11, amd64

#### Which cloud storage system are you using? (e.g. Google Drive)

sftp (Linux openssh)

#### Reproduce

I have files in Windows which filenames contain `／` (Fullwidth Solidus),  `？` (FULLWIDTH QUESTION MARK)  and other full width version of special characters that are restricted on Windows filenames. I want to upload these files to remote while **keeping the file name unchanged**, but with sftp backend, it's impossible.

Let's say we have a directory with only one `／？.txt` ( a Fullwidth Solidus + a FULLWIDTH QUESTION MARK) file in Windows.

I have a sftp backend, it's a standard Linux server with OpenSSH, rclone.conf config:

```
[testsftp]
type = sftp
host = 192.168.1.10
user = root
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
encoding = None
pass = password
```

If I upload the file without `--local-encoding None` option:

```
rclone copy . testsftp:/tmp
```

Then, the uploaded file in Linux will have the name `／?.txt` . The original fullwidth `？` character in filename was replaced by normal question mark `?`

If I upload the file with `--local-encoding None` option:

```
rclone copy --local-encoding None . testsftp:/tmp
```

Then, the uploaded file in Linux will have the name `‛／？.txt` . The `／` character was escaped to `‛／` .

In both cases, the uploaded file will have it's original filename changed.

#### Other info

I also tried to add `encoding = None` to sftp backend config in rclone.conf but with no luck.

I think this problem is specific to Windows + sftp backend. I tried upload files from Windows -> google drive, with `--local-encoding None` flag set, rclone correctly uploads file with filenames unchanged. Rclone also works when upload files from Linux -> sftp (Linux).

**Comment by ncw** [comment]
This is in the process of being fixed with `encoding = Raw` in #7791 - you'll find binaries you can try there

**Comment by YenForYang** [comment]
`encoding = Raw` does not seems to fix the issue. And it doesn't appear to be limited to Windows local source to sftp destination. It may be actually only limited to this one particular character -- the fullwidth solidus `／`.

I've been really frustrated over how to get consistent behavior in transfers with `／` in file or folder names. _It seems to depend on some `encoding` requirement or combination on both the source and destination._ The `Slash` option seems to give the proper results _sometimes_ but I would assume `Raw` to be the best option -- I simply want nothing to be changed: **If I put a `／` in a file or folder name I simply want it as is -- not split into a folder and a file (i.e. interpreted into a relative path), not a file/folder with a `/` (plain solidus), or a file/folder with a `‛／` **. I thought `Raw` achieves this. It does not, unfortunately.

**Comment by YenForYang** [comment]
Strange enough `Raw` does not fix this issue, and it appears that this issue isn't limited to Windows source with a sftp remote. For some reason `encoding = Slash` appears to get the `‛` character to go away, but I haven't gotten consistent results yet.

**Comment by ncw** [comment]
Le me know if you can pin it down @YenForYang - thanks

**Comment by fiso64** [comment]
I can reproduce this with
```
rclone v1.71.2
- os/version: Microsoft Windows 10 IoT Enterprise LTSC 2021 21H2 21H2 (64 bit)
- os/kernel: 10.0.19044.6456 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.25.3
- go/linking: static
- go/tags: cmount
```

I took a usb stick, formatted it to ntfs and mounted it on my linux server using `ntfs-3g`.

Then I created a windows folder with the following contents:
```
> $ rclone tree test
/
├── file／.ext
└── file：.ext
```
(these are U+FF1A, U+FF0F, not the standard forward slash and colon, so they're allowed on all filesystems).

I then tried to sync it to the usb stick on the sftp remote. `file／.ext` transfers successfully, while `file：.ext` fails to transfer:
```
> $ rclone sync test odroid:/mnt/usb/test --retries 1 --inplace -vv
2025/11/06 19:54:58 DEBUG : rclone: Version "v1.71.2" starting with parameters ["rclone" "sync" "test" "odroid:/mnt/usb/test" "--retries" "1" "--inplace" "-vv"]
2025/11/06 19:54:58 DEBUG : Creating backend with remote "test"
2025/11/06 19:54:58 DEBUG : Using config file from "C:\\Users\\fiso\\AppData\\Roaming\\rclone\\rclone.conf"
2025/11/06 19:54:58 DEBUG : fs cache: renaming cache item "test" to be canonical "//?/C:/Users/fiso/Desktop/folder/test"
2025/11/06 19:54:58 DEBUG : Creating backend with remote "odroid:/mnt/usb/test"
2025/11/06 19:54:59 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: New connection 192.168.1.15:65507->192.168.1.25:22 to "SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.14"
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Shell type "unix" from config
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Using root directory "/mnt/usb/test"
2025/11/06 19:55:01 DEBUG : file:.ext: Need to transfer - File not found at Destination
2025/11/06 19:55:01 DEBUG : file／.ext: Need to transfer - File not found at Destination
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Waiting for checks to finish
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Waiting for transfers to finish
2025/11/06 19:55:01 ERROR : file:.ext: Failed to copy: Update Create failed: sftp: "Bad message" (SSH_FX_BAD_MESSAGE)
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: New connection 192.168.1.15:65517->192.168.1.25:22 to "SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.14"
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Shell path "/mnt/usb/test/file／.ext"
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Running remote command: md5sum /mnt/usb/test/file／.ext
2025/11/06 19:55:01 DEBUG : sftp://odroid@192.168.1.25:22//mnt/usb/test: Remote command result: d41d8cd98f00b204e9800998ecf8427e  /mnt/usb/test/file／.ext
2025/11/06 19:55:01 DEBUG : file／.ext: Parsed hash: d41d8cd98f00b204e9800998ecf8427e
2025/11/06 19:55:01 DEBUG : file／.ext: md5 = d41d8cd98f00b204e9800998ecf8427e OK
2025/11/06 19:55:01 INFO  : file／.ext: Copied (new)
2025/11/06 19:55:01 ERROR : sftp://odroid@192.168.1.25:22//mnt/usb/test: not deleting files as there were IO errors
2025/11/06 19:55:01 ERROR : sftp://odroid@192.168.1.25:22//mnt/usb/test: not deleting directories as there were IO errors
2025/11/06 19:55:01 ERROR : Attempt 1/1 failed with 1 errors and: Update Create failed: sftp: "Bad message" (SSH_FX_BAD_MESSAGE)
2025/11/06 19:55:01 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Checks:                 0 / 0, -, Listed 2
Transferred:            1 / 1, 100%
Elapsed time:         0.3s
```
```
odroid@server:/mnt/usb/test$ tree .
.
└── file／.ext
```

The result becomes different when the same command is run with `--local-encoding None`. In this case, `file：.ext` gets transferred successfully, but the slash in `file／.ext` is needlessly escaped:
```
rclone sync test odroid:/mnt/usb/test --retries 1 --inplace -vv --local-encoding None
...
```
```
odroid@server:/mnt/usb/test$ tree .
.
├── file‛／.ext
└── file：.ext
```

## Notes

1. This issue is NOT specific to sftp remotes. I can also reproduce it with webdav remotes
    ```
    rclone sync test rclone-webdav:test
    ...
    2025/11/06 15:02:40 DEBUG : file:.ext: Need to transfer - File not found at Destination
    2025/11/06 15:02:40 DEBUG : file:.ext: Update will use the normal upload strategy (no chunks)
    2025/11/06 15:02:41 ERROR : file:.ext: Failed to copy: unchunked simple update failed: Method Not Allowed: 405 Method Not Allowed
    ```
    I have tried both `rclone serve` and `wsgidav` as the backend. 


2. Even without involving a remote, the `rclone ls` command produces similar output in both cases: 
    ```
    rclone ls test
            0 file／.ext
            0 file:.ext
    
    rclone ls test --local-encoding=None 
            0 file‛／.ext
            0 file：.ext
    ```
  

3. Other methods to copy the files work fine. I have tested it with `scp`, as well as the `sftp` interactive session.

**Comment by fiso64** [comment]
Like YenForYang I can also fix it with `--local-encoding Slash`.

Here is a list of characters I was able to find that were affected by the issue (might be incomplete):
```
？
＜
＞
：
＊
｜
```
For the escaping issue I only found `／`.

Again, all characters are handled correctly with `--local-encoding Slash`. Adding this option fixes the escape issue for `／`, and resolves any copy errors for all other "odd" characters that I found.
