### ISSUE TITLE
Bisync segfaults

### ISSUE THREAD

**Issue by LivingUserError** [rclone/rclone#7947]
#### What is the problem you are having with rclone?

Rclone segfaults when running the command below, both when the Proton access token has gone stale (which is expected and happens frequently) and during normal operation.

#### What is your rclone version (output from `rclone version`)

rclone v1.66.0
- os/version: arch rolling (64 bit)
- os/kernel: 6.9.8-arch1-1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: dynamic
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)

Proton Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```shell
rclone bisync proton:sync /home/user/Proton "--protondrive-replace-existing-draft=true" "--resilient" "--create-empty-src-dirs" "--refresh-times" "--metadata" "--transfers" "8" "--human-readable"
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
(Just the error and stuff from immediately before. Filtering all personal info from the whole log is basically impossible here. Hit me up for a more extensive log...)
##### With expired token
```shell
2024/07/11 20:34:21.058078 ERROR RESTY 401 GET https://mail.proton.me/api/drive/shares/stuff_that_looks_like_some_token/files/more_stuff_that_looks_like_some_token/revisions: Invalid access token (Code=401, Status=401)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a437625dd26]

goroutine 10166 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc00298e500, {0x5a43778a28f0, 0xc0020cc500}, {0xc00013bf00,0x1, 0x0?})
github.com/rclone/rclone/backend/protondrive/protondrive.go:883 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc002b010a0)
github.com/rclone/rclone/fs/operations/reopen.go:145 +0xc5
github.com/rclone/rclone/fs/operations.NewReOpen({0x5a43778a28f0, 0xc0020cc500}, {0x5a43778b8db0, 0xc00298e500}, 0xa, {0xc00013bf00, 0x1, 0x1})
github.com/rclone/rclone/fs/operations/reopen.go:102 +0x50b
github.com/rclone/rclone/fs/operations.Open({0x5a43778a28f0, 0xc0020cc500}, {0x5a43778b8db0, 0xc00298e500}, {0xc00013bf00, 0x1, 0x1})
github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc001add950, {0x5a43778a28f0, 0xc0020cc500})
github.com/rclone/rclone/fs/operations/copy.go:253 +0x4e5
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc001add950, {0x5a43778a28f0, 0xc0020cc500})
github.com/rclone/rclone/fs/operations/copy.go:302 +0x16c
github.com/rclone/rclone/fs/operations.Copy({0x5a43778a28f0, 0xc0020cc500}, {0x5a43778b8330, 0xc000aa7ae0}, {0x0, 0x0}, {0xc0027b7818, 0x15}, {0x5a43778b8db0, 0xc00298e500})
github.com/rclone/rclone/fs/operations/copy.go:404 +0x485
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000c18008, {0x5a43778a28f0, 0xc0020cc500}, 0xc0020cc280, {0x5a43778b8330, 0xc000aa7ae0}, 0x0, 0xc001b66fa8?)
github.com/rclone/rclone/fs/sync/sync.go:498 +0x205
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
github.com/rclone/rclone/fs/sync/sync.go:528 +0x6b
```
##### With valid token:
```shell
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
2024/07/11 21:09:05 DEBUG : writing result:
{
"Src": "proton{NaVA0}:sync/",
"Dst": "",
"Name": "50-dracut (1).install",
"AltName": "",
"Size": 0,
"Modtime": "2024-07-09T17:45:30Z",
"Hash": "",
"Flags": "-",
"Sigil": 43,
"Err": null,
"Winner": {
"Obj": {},
"Side": "src",
"Err": null
},
"IsWinner": true,
"IsSrc": true,
"IsDst": false,
"Origin": "sync"
}
2024/07/11 21:09:05 DEBUG : writing result:
{
"Src": "proton{NaVA0}:sync/",
"Dst": "",
"Name": "50-dracut (1).install",
"AltName": "",
"Size": 0,
"Modtime": "2024-07-09T17:45:30Z",
"Hash": "",
"Flags": "-",
"Sigil": 43,
"Err": null,
"Winner": {
"Obj": {},
"Side": "src",
"Err": null
},
"IsWinner": false,
"IsSrc": false,
"IsDst": true,
"Origin": "sync"
}
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Need to transfer - File not found at Destination
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
2024/07/11 21:09:05 DEBUG : Local file system at /home/user/Proton: Waiting for checks to finish
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
2024/07/11 21:09:05 DEBUG : Local file system at /home/userl/Proton: Waiting for transfers to finish
2024/07/11 21:09:05 DEBUG : 50-dracut (1).install: Original file size missing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6143c927cd26]

goroutine 10495 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc000616780, {0x6143ca8c18f0, 0xc002873680}, {0xc0008c4fc0,0x1, 0x0?})
github.com/rclone/rclone/backend/protondrive/protondrive.go:883 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc0023767e0)
github.com/rclone/rclone/fs/operations/reopen.go:145 +0xc5
github.com/rclone/rclone/fs/operations.NewReOpen({0x6143ca8c18f0, 0xc002873680}, {0x6143ca8d7db0, 0xc000616780}, 0xa, {0xc0008c4fc0, 0x1, 0x1})
github.com/rclone/rclone/fs/operations/reopen.go:102 +0x50b
github.com/rclone/rclone/fs/operations.Open({0x6143ca8c18f0, 0xc002873680}, {0x6143ca8d7db0, 0xc000616780}, {0xc0008c4fc0, 0x1, 0x1})
github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc002a2eea0, {0x6143ca8c18f0, 0xc002873680})
github.com/rclone/rclone/fs/operations/copy.go:253 +0x4e5
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc002a2eea0, {0x6143ca8c18f0, 0xc002873680})
github.com/rclone/rclone/fs/operations/copy.go:302 +0x16c
github.com/rclone/rclone/fs/operations.Copy({0x6143ca8c18f0, 0xc002873680}, {0x6143ca8d7330, 0xc000c5ad20}, {0x0, 0x0}, {0xc0025e2f48, 0x15}, {0x6143ca8d7db0, 0xc000616780})
github.com/rclone/rclone/fs/operations/copy.go:404 +0x485
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000998788, {0x6143ca8c18f0, 0xc002873680}, 0xc0028735e0, {0x6143ca8d7330, 0xc000c5ad20}, 0xc, 0xc0007ce7a8?)
github.com/rclone/rclone/fs/sync/sync.go:498 +0x205
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
github.com/rclone/rclone/fs/sync/sync.go:528 +0x6b
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
This looks like the following `protondrive` issue:

- https://github.com/rclone/rclone/issues/6072#issuecomment-1746979815
- https://github.com/henrybear327/Proton-API-Bridge/issues/23

**Comment by LivingUserError** [comment]
Might be the case, however the error does not occur any more, while the issue is still open... I don't think that I did anything except maybe performing a `--resync` run..?

**Comment by nielash** [comment]
It is possible that the bug only occurs under certain conditions...

Are you able to reproduce the same issue with a different remote (not `protondrive`)? If not, that would support my suspicion that this is a `protondrive` bug and not a `bisync` bug.

**Comment by LivingUserError** [comment]
Can't reproduce it to begin with. All I know is that it happend multiple times over multiple restarts and `--resync`s until it didn't anymore. So whatever it was I guess it is fixed on the way from

```
rclone v1.66.0

    os/version: arch rolling (64 bit)
    os/kernel: 6.9.8-arch1-1 (x86_64)
    os/type: linux
    os/arch: amd64
    go/version: go1.22.1
    go/linking: dynamic
    go/tags: none
```

to

```
rclone v1.67.0
- os/version: endeavouros (64 bit)
- os/kernel: 6.10.7-arch1-1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.5
- go/linking: dynamic
- go/tags: none
```

**Comment by nielash** [comment]
> So whatever it was I guess it is fixed

Ok. In that case, I will go ahead and close this for now. Feel free to reopen it if you see it again in the latest version.

**Comment by nikolaioak** [comment]
I am still seeing this issue on the latest version. Not sure what the rhyme or reason is, I tried to push it along by downloading individual files that it would error on, and that does push it through but with 18K files, I don't want to keep doing that... Any sort of dry run doesn't catch this (assuming it has to do with the actual action of copying/syncing).

```
rclone v1.68.2
- os/version: debian trixie/sid (64 bit)
- os/kernel: 6.12.5-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.3
- go/linking: static
- go/tags: none
```

Log (stuck on "example file" Directory/file.ext):
```
 *                Directory/file.ext: checkingpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x187cb06]

goroutine 126 [running]:
github.com/rclone/rclone/backend/protondrive.(*Object).Open(0xc000bb2f00, {0x2a662f0, 0xc000f0a730}, {0xc000e12aa0, 0x1, 0xc000c4b9b8?})
        github.com/rclone/rclone/backend/protondrive/protondrive.go:886 +0x46
github.com/rclone/rclone/fs/operations.(*ReOpen).open(0xc001202d20)
        github.com/rclone/rclone/fs/operations/reopen.go:147 +0x109
github.com/rclone/rclone/fs/operations.NewReOpen({0x2a662f0, 0xc000f0a730}, {0x2a7da30, 0xc000bb2f00}, 0xa, {0xc000e12a70, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:102 +0x50b
github.com/rclone/rclone/fs/operations.Open({0x2a662f0, 0xc000f0a730}, {0x2a7da30, 0xc000bb2f00}, {0xc000e12a70, 0x1, 0x1})
        github.com/rclone/rclone/fs/operations/reopen.go:124 +0x6b
github.com/rclone/rclone/fs/operations.(*copy).manualCopy(0xc00126b440, {0x2a662f0, 0xc000f0a730})
        github.com/rclone/rclone/fs/operations/copy.go:261 +0x4dc
github.com/rclone/rclone/fs/operations.(*copy).copy(0xc00126b440, {0x2a662f0, 0xc000f0a730})
        github.com/rclone/rclone/fs/operations/copy.go:310 +0x176
github.com/rclone/rclone/fs/operations.Copy({0x2a662f0, 0xc000f0a730}, {0x2a7ced0, 0xc000bb2000}, {0x0, 0x0}, {0xc00138df40, 0x32}, {0x2a7da30, 0xc000bb2f00})
        github.com/rclone/rclone/fs/operations/copy.go:412 +0x493
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000494a08, {0x2a662f0, 0xc000f0a730}, 0xc000f0a690, {0x2a7ced0, 0xc000bb2000}, 0x4b, 0x0?)
        github.com/rclone/rclone/fs/sync/sync.go:501 +0x1fe
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers in goroutine 1
        github.com/rclone/rclone/fs/sync/sync.go:531 +0x6b

```
Really appreciate all the work that is going on in lieu of an actual client by Proton... let me know if I can provide any other information to support this fix.

**Comment by ncw** [comment]
@nikolaioak I think what you are seeing is this bug https://github.com/rclone/rclone/issues/7959 which is a bug in protondrive

**Comment by nikolaioak** [comment]
Thanks, yes does seem like it's specific to the proton docs. I've renamed those to use a .protondoc extension and added them to an exclude filter for now (I think by default no extension is given to the files).

**Comment by jessebs** [comment]
A work around that works for me - try the flag `--min-size 1b`. This will skip files <1byte in size
