### ISSUE TITLE
Push docker image to ghcr (github) container registry

### ISSUE THREAD

**Issue by JuniorJPDJ** [rclone/rclone#8150]
Dockerhub have strict ratelimits, would be nice to have it also on ghcr.

**Comment by ncw** [comment]
I believe we push the betas to ghcr. There doesn't appear to be a webui to check through!

I don't think we push the releases for some reason.

Can you confirm?

**Comment by JuniorJPDJ** [comment]
There's webUI, it should be here: https://github.com/orgs/rclone/packages

Also packages can be connected with the code repository and show up directly on repo main page.

**Comment by darthShadow** [comment]
Should be fixed by https://github.com/rclone/rclone/pull/8166.

**Comment by JuniorJPDJ** [comment]
It's not or at least package is not made public.

**Comment by davralin** [comment]
Just to confirm, it's still not visible.
@darthShadow  - are you seeing the packages?

**Comment by ncw** [comment]
That is now public @darthShadow @davralin 

I don't know whether I've missed something or we need to wait for it to propagate, but I can't pull the image

```
$ docker pull ghcr.io/rclone/rclone:sha-b5e72e2
Error response from daemon: Head "https://ghcr.io/v2/rclone/rclone/manifests/sha-b5e72e2": denied: denied
```

**Comment by davralin** [comment]
Confirm I can also pull `ghcr.io/rclone/rclone:master` - not seeing 1.69.0 as a tag though, but that will probably be fixed by the next release.

**Comment by ncw** [comment]
@davralin @darthShadow I just released the v1.69.1 point release and it appears to have arrived successfully in ghcr and docker hub :-)

Which I think makes this issue done.

Thanks for all your hard work in reworking all the build scripts @darthShadow - it is great that they only take a few minutes rather than an hour!
