### ISSUE TITLE
Back Blaze Multi threaded upload will have a recoverable error - fails anyway

### ISSUE THREAD

**Issue by zackees** [rclone/rclone#8383]
Continuation of:

https://github.com/rclone/rclone/issues/8315#issuecomment-2655173223

PR for fix: https://github.com/rclone/rclone/pull/8384

Almost like clockwork, rclone will fail at 3% for this file below. Even when the b2 concurrency value is set to just one.

@ncw mentioned that it looks like a proxy error with the HTML being sent back as an error code, or vice versa.

Looking at this logs, retry=False was being triggered for this error, borking the entire multi-part download consisting of 4k upload parts. Yes, if any one of those upload parts fails then the entire thing fails.

The reason is this: low-level retries are ONLY enabled if and only if, the error type and message can evaluate for true in list of predicate that will be run on the error. If no rule returns true, then the retries=False is returned.

This means that *any* unexpected error not covered by the white list will bypass the low level retries. That's what happened in the B2 case.

My fix does not address the bigger picture - it only adds this specific error type to the white list.

It may be useful to consider that retry=True be returned for any 500 "internal error" status code returned for an upload part.

```
650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0054": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.663 MiB/s, ETA 1w4d1h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m48.3s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.561Mi/s, 11h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.663 MiB/s, ETA 1w4d1h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m48.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.561Mi/s, 11h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:47:59 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 25 (retry=false): Post "https://pod-020-3011-15.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0045": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-15.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0045", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:47:59 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 25: Post "https://pod-020-3011-15.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0045": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:47:59 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 19 (retry=false): Post "https://pod-020-3011-05.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0033": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-05.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0033", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.2s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:47:59 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 19: Post "https://pod-020-3011-05.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0033": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.2s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 8.121 MiB/s, ETA 1w4d19h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:48:00 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 109 (retry=false): Post "https://pod-020-3011-14.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0041": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-14.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0041", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.8s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | 2025/02/12 20:48:00 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 109: Post "https://pod-020-3011-14.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0041": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m49.8s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 8.026Mi/s, 12h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.524Mi/s, 13h
2|run2  | 2025/02/12 20:48:00 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 52/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-13.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0034": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.524Mi/s, 13h
2|run2  | 2025/02/12 20:48:00 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 185/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0044": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.3s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.524Mi/s, 13h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.614 MiB/s, ETA 1w5d14h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.524Mi/s, 13h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 40 (retry=false): Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0059": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0059", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.9s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 40: Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0059": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m50.9s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 190 (retry=false): Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0022": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0022", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.2s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 190: Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0022": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.2s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 80/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-16.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0031": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 17 (retry=false): Post "https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0029": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0029", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:01 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 17: Post "https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0029": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 7.138 MiB/s, ETA 1w6d10h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Sending chunk 210 length 33554432
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 210 (retry=false): Post "https://pod-020-3011-09.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0054": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-09.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0054", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 210: Post "https://pod-020-3011-09.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0054": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 143 (retry=false): Post "https://pod-020-3011-19.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0007": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-19.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0007", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.7s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 143: Post "https://pod-020-3011-19.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0007": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m51.7s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 7.054Mi/s, 14h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 183/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-06.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0010": context canceled
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 210/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-13.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0013": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 212/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0028": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 155 (retry=false): Post "https://pod-020-3011-11.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0038": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-11.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0038", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:02 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 155: Post "https://pod-020-3011-11.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0038": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.5s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 125/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-15.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0053": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Sending chunk 205 length 33554432
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 205 (retry=false): Post "https://pod-020-3011-07.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0037": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-07.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0037", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 205: Post "https://pod-020-3011-07.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0037": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 89 (retry=false): Post "https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0024": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0024", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 89: Post "https://pod-020-3011-03.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0024": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.692 MiB/s, ETA 2w7h42m
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.6s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: multi-thread copy: chunk 186/11650 failed: multi-thread copy: failed to write chunk: Post "https://pod-020-3011-16.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0008": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.273 MiB/s, ETA 2w1d6h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m52.7s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.613Mi/s, 15h
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.273 MiB/s, ETA 2w1d6h
2|run2  | Checks:                 3 / 3, 100%, Listed 312
2|run2  | Transferred:            0 / 22, 0%
2|run2  | Elapsed time:      3m53.0s
2|run2  | Transferring:
2|run2  |  * zlib2-data/pilimi-zlib2-15000000-15679999.tar:  1% /364.036Gi, 6.200Mi/s, 16h
2|run2  | 2025/02/12 20:48:03 DEBUG : zlib2-data/pilimi-zlib2-15000000-15679999.tar: Error sending chunk 157 (retry=false): Post "https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0006": multi-thread copy: failed to write chunk: invalid character '<' looking for beginning of value: &url.Error{Op:"Post", URL:"https://pod-020-3011-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f228491889785e70a_d20250212_m204420_c002_v0203011_t0019_u01739393060115/0006", Err:(*fmt.wrapError)(0xc007674740)}
2|run2  | Transferred:              4.402 GiB / 7.901 TiB, 0%, 6.273 MiB/s, ETA 2w1d6h
```

**Comment by ncw** [comment]
Thanks for your log with `-vv --dump headers`.  (Note that using `--log-file` will stop it having the `--progress` messages in it which made it rather hard to read.)

Anyway I have unraveled what is going on.

First rclone sends an upload part request

```
2025/02/13 21:51:48 DEBUG : HTTP REQUEST (req 0xc001d98280)
2025/02/13 21:51:48 DEBUG : POST /b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f230abb7049bb8ee4_d20250213_m214947_c002_v0203012_t0058_u01739483387363/0018 HTTP/1.1
Host: pod-020-3012-10.backblaze.com
User-Agent: rclone/v1.69.0
Content-Length: 100663336
Authorization: XXXX
X-Bz-Content-Sha1: hex_digits_at_end
X-Bz-Part-Number: 129
Accept-Encoding: gzip
```

Next backblaze replies with a redirect to an internal error page which is odd. I would have expected a 500 error here.

```
2025/02/13 21:52:48 DEBUG : HTTP RESPONSE (req 0xc001d98280)
2025/02/13 21:52:48 DEBUG : HTTP/1.1 302 
Content-Length: 0
Connection: keep-alive
Date: Thu, 13 Feb 2025 21:52:48 GMT
Location: https://www.backblaze.com/status/internal-error
Server: nginx
Strict-Transport-Security: max-age=63072000
```

Which rclone then fetches

```
2025/02/13 21:52:48 DEBUG : HTTP REQUEST (req 0xc002464140)
2025/02/13 21:52:48 DEBUG : GET /status/internal-error HTTP/1.1
Host: www.backblaze.com
User-Agent: rclone/v1.69.0
Referer: https://pod-020-3012-10.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f230abb7049bb8ee4_d20250213_m214947_c002_v0203012_t0058_u01739483387363/0018
X-Bz-Content-Sha1: hex_digits_at_end
X-Bz-Part-Number: 129
Accept-Encoding: gzip
```

And the result is at 200 OK with `Content-Type: text/html`  which is not at all what we expect from the B2 API.

```
2025/02/13 21:52:48 DEBUG : HTTP RESPONSE (req 0xc002464140)
2025/02/13 21:52:48 DEBUG : HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=86400
Cf-Apo-Via: origin,miss
Cf-Cache-Status: BYPASS
Cf-Ray: 91180c31494057df-FRA
Content-Security-Policy: frame-ancestors 'self' https://secure.backblaze.xyz https://secure.backblaze.pet https://secure.backblaze.net https://secure.backblaze.com
Content-Type: text/html
Date: Thu, 13 Feb 2025 21:52:48 GMT
Last-Modified: Wed, 12 Feb 2025 21:29:30 GMT
Server: cloudflare
Set-Cookie: _cfuvid=XXX
Set-Cookie: bz-n-c=XXX
Set-Cookie: _cfuvid=XXX
Strict-Transport-Security: max-age=2592000
Surrogate-Control: max-age=432000
Surrogate-Key: webflow-prod.backblaze.com 63d32de856f6323a43a277f2 pageId:659ef884320ab56913e84538 659ef884320ab56913e84523
Vary: Accept-Encoding
X-Bz-N: i
X-Bz-Www-Routing: 83e83299
X-Cluster-Name: eu-south-1-prod-hosting-red
X-Frame-Options: SAMEORIGIN
X-Lambda-Id: c8e73afd-18f8-4db9-b57c-23b8fe71470e
```

The body of that is an HTML page which you'll see if you go to the redirected URL in your browser https://www.backblaze.com/status/internal-error

The problem here is that backblaze did not return a 500 error, it sent a 301 redirect to an HTML error page which rclone fetched with 200 OK. It then attempted to parse that as JSON and hence the error `invalid character '<' looking for beginning of value` as HTML is not valid JSON!

The API is supposed to return 500 error codes, not human readable HTML so this is really a bug in the Backblaze B2 API.

Maybe @metadaddy could take a look?

Anyway if we want to make a workaround for this, then what we need to do is detect that the server has sent us an HTML page instead of JSON when we are trying to decode the JSON.

Have a go with this and see if it works

[v1.70.0-beta.8595.53bbe891d.fix-8383-b2-error](https://beta.rclone.org/branch/fix-8383-b2-error/v1.70.0-beta.8595.53bbe891d.fix-8383-b2-error/) on branch [fix-8383-b2-error](https://github.com/rclone/rclone/tree/fix-8383-b2-error) (uploaded in 15-30 mins)

**Comment by zackees** [comment]
I built from source in the branch right now I'm at 9GB of a 9TB download so it looks like the issue has been fixed!

**Comment by ncw** [comment]
Great news!

You should still see those 

    invalid character '<' looking for beginning of value 

Logs in the debug log but they should be retried now.

Do you?

**Comment by zackees** [comment]
Nick, check your inbox

**Comment by ncw** [comment]
The errors are being retried in your logs which is good.

However I'm not seeing the error I expected though which should be something like

    "failed to decode JSON from Content-Type: text/html: invalid character '<' looking for beginning of value

Which makes me think those logs might not be from the version above?

**Comment by zackees** [comment]
```
valid character '<' looking for beginning of value: fserrors.wrappedRetryError{error:(*errors.errorString)(0xc0024659f0)}
1|run  | Transferred:             100.023 GiB / 2.614 TiB, 4%, 57.870 MiB/s, ETA 12h39m49s
1|run  | Transferred:            0 / 6, 0%
1|run  | Elapsed time:     54m12.6s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21180000-21229999.tar:  0% /539.873Gi, 17.659Mi/s, 8h
1|run  |  *            pilimi-zlib2-21400000-21489999.tar:  1% /472.115Gi, 40.575Mi/s, 3h
1|run  | 2025/02/18 14:02:55 DEBUG : pilimi-zlib2-21180000-21229999.tar: Error sending chunk 98: failed to decode JSON from Content-Type: "text/html": invalid character '<' looking for beginning of value
1|run  | Transferred:             100.023 GiB / 2.614 TiB, 4%, 57.870 MiB/s, ETA 12h39m49s
1|run  | Transferred:            0 / 6, 0%
1|run  | Elapsed time:     54m12.6s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21180000-21229999.tar:  0% /539.873Gi, 17.659Mi/s, 8h
1|run  |  *            pilimi-zlib2-21400000-21489999.tar:  1% /472.115Gi, 40.575Mi/s, 3h
1|run  | 2025/02/18 14:02:55 DEBUG : pilimi-zlib2-21080000-21179999.tar: multi-thread copy: chunk 907/5573 failed: multi-thread copy: failed to write chunk: Post "https://pod-000-1149-01.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f2339bc9a4691a553_d20250218_m135806_c002_v0001149_t0055_u01739887086298/0032": multi-thread copy: failed to write chunk: failed to decode JSON from Content-Type: "text/html": invalid character '<' looking for beginning of value
1|run  | Transferred:              51.232 GiB / 4.919 TiB, 1%, 19.576 MiB/s, ETA 3d26m48s
1|run  | Transferred:            0 / 10, 0%
1|run  | Elapsed time:     54m12.0s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21080000-21179999.tar:  1% /522.442Gi, 39.583Ki/s, 37
1|run  |  *            pilimi-zlib2-21230000-21319999.tar:  0% /495.683Gi, 19.592Mi/s, 7h
1|run  | 2025/02/18 14:02:55 DEBUG : pilimi-zlib2-21230000-21319999.tar: Sending chunk 143 length 100663296
1|run  | Transferred:              51.232 GiB / 4.919 TiB, 1%, 19.576 MiB/s, ETA 3d26m48s
1|run  | Transferred:            0 / 10, 0%
1|run  | Elapsed time:     54m12.0s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21080000-21179999.tar:  1% /522.442Gi, 39.583Ki/s, 37
1|run  |  *            pilimi-zlib2-21230000-21319999.tar:  0% /495.683Gi, 19.592Mi/s, 7h
1|run  | 2025/02/18 14:02:55 DEBUG : pilimi-zlib2-21080000-21179999.tar: multi-thread copy: chunk 597/5573 failed: multi-thread copy: failed to write chunk: Post "https://pod-000-1149-16.backblaze.com/b2api/v1/b2_upload_part/4_zb87219cbda6098ab96340e17_f2339bc9a4691a553_d20250218_m135806_c002_v0001149_t0055_u01739887086298/0002": multi-thread copy: failed to write chunk: failed to decode JSON from Content-Type: "text/html": invalid character '<' looking for beginning of value
1|run  | Transferred:              51.233 GiB / 4.919 TiB, 1%, 19.576 MiB/s, ETA 3d26m48s
1|run  | Transferred:            0 / 10, 0%
1|run  | Elapsed time:     54m12.1s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21080000-21179999.tar:  1% /522.442Gi, 39.583Ki/s, 37
1|run  |  *            pilimi-zlib2-21230000-21319999.tar:  0% /495.683Gi, 19.592Mi/s, 7h
1|run  | 2025/02/18 14:02:55 DEBUG : pilimi-zlib2-21230000-21319999.tar: Sending chunk 565 length 100663296
1|run  | Transferred:              51.233 GiB / 4.919 TiB, 1%, 19.576 MiB/s, ETA 3d26m48s
1|run  | Transferred:            0 / 10, 0%
1|run  | Elapsed time:     54m12.1s
1|run  | Transferring:
1|run  |  *            pilimi-zlib2-21080000-21179999.tar:  1% /522.442Gi, 39.583Ki/s, 37
1|run  |  *            pilimi-zlib2-21230000-21319999.tar:  0% /495.683Gi, 19.592Mi/s, 7h
^C
root@sync-zlib2-data--1:~# ^C
root@sync-zlib2-data--1:~# ^C
root@sync-zlib2-data--1:~# ^C
root@sync-zlib2-data--1:~# ^C
root@sync-zlib2-data--1:~# rclone --version
rclone v1.70.0-beta.8595.53bbe891d.fix-8383-b2-error
- os/version: ubuntu 24.10 (64 bit)
- os/kernel: 6.11.0-9-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.24.0
- go/linking: static
- go/tags: none
root@sync-zlib2-data--1:~# 
```

**Comment by ncw** [comment]
Can you send me a log of that please?

**Comment by zackees** [comment]
Next week when I'm back in the office

**Comment by metadaddy** [comment]
Hi @ncw - apologies, I've been a bit swamped and only just had an opportunity to dig into this. We *definitely* shouldn't be returning `302` from `b2_upload_part`. I'll get the B2 engineers on the case.

**Comment by zackees** [comment]
> Hi again, @ncw - we've identified an issue where we return a `302` if the client doesn't send bytes for 60 seconds. Given the 1 minute gap between the `b2_upload_part` request and `302` response, ~it looks like this is the problem~. Looking in our logs, we can actually see that this is exactly the problem - we get a timeout on the socket.
> 
> We're fixing our side to return the correct HTTP status code, `408`.
> 
> @zackees I looked back through the comments here and on #8315, but it's not clear to me... What source are you working with? Is it possible that the source is being slow producing the data?

Yes, source is slower than BB and is the bottleneck.
