### ISSUE TITLE
Forget listing, I just want to upload to Google Photos

### ISSUE THREAD

**Issue by naisanzaa** [rclone/rclone#8620]
#### What is your current rclone version (output from `rclone version`)?
```
eric@dorabuk rclone-actions % rclone version
rclone v1.69.1
- os/version: darwin 15.5 (64 bit)
- os/kernel: 24.5.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.24.0
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?
Google Photos is more so just a dumpster for me to pour pictures in. I like their face recognition to sort images. 

Even though we can't list photos anymore, but I still want to just upload pictures to Google Photos.

Is this still possible?

**Comment by ncw** [comment]
This should be possible, yes. I tested exactly this scenario recently when I updated the docs.

**Comment by naisanzaa** [comment]
updated. I read https://rclone.org/googlephotos/, but not sure what command I should be using. I'm guessing `copy` but I still get `403 PERMISSION_DENIED`

```
rclone v1.70.1
- os/version: darwin 15.5 (64 bit)
- os/kernel: 24.5.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.24.4
- go/linking: dynamic
- go/tags: none
```

rclone: 
```
RCLONE="rclone --config rclone.conf"

${RCLONE} copy -v remote:pictures          photos:album/pictures
```

**Comment by naisanzaa** [comment]
just saw the tiny note

> NB From March 31, 2025 rclone can only download photos it uploaded. This limitation is due to policy changes at Google. You may need to run rclone config reconnect remote: to make rclone work again after upgrading to rclone v1.70.

**Comment by ncw** [comment]
Let me know if that doesn't work. It worked for me when I tried it about 2 weeks ago.

**Comment by naisanzaa** [comment]
That worked!
