### ISSUE TITLE
"Inline config authentication with Blomp Swift backend fails with 'Can't find AuthVersion in AuthUrl' error"

### ISSUE THREAD

**Issue by Spy-God** [rclone/rclone#8859]
#### What is the problem you are having with rclone?

Can't find AuthVersion in AuthUrl - set explicitly error using inline config with Blomp Swift backend in rclone

#### What is your rclone version (output from `rclone version`)

```
└──╼  rclone --version                          29/Sep/25  Mon 04:13  AM rclone v1.71.1-termux                                                            - os/version: unknown
- os/kernel: 6.6.30-android15-8-o-g42804ac7db66-4k (aarch64)
- os/type: android
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.25.0
- go/linking: dynamic
- go/tags: noselfupdate
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Android 15 Termux Arm64 

#### Which cloud storage system are you using? (e.g. Google Drive)

Blomp Cloud Storage

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000%2F10%2F10,auth=https://authenticate.blomp.com/,tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
└──╼  rclone -vv ls ':swift,user=spygoddd@proton.me,key=DOB0000%2F00%210,auth=https://authenticate.blomp.com/,tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
2025/09/28 22:46:10 DEBUG : rclone: Version "v1.71.1-termux" starting with parameters ["rclone" "-vv" "ls" ":swift,user=spygoddd@proton.me,key=DOB2003%2F09%2F05,auth=https://authenticate.blomp.com/,tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me"]
2025/09/28 22:46:10 DEBUG : Creating backend with remote ":swift,user=spygoddd@proton.me,key=DOB1000%2F10%2F10,auth=https://authenticate.blomp.com/,tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me"
2025/09/28 22:46:10 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2025/09/28 22:46:10 DEBUG : :swift: detected overridden config - adding "{pYFGY}" suffix to name
2025/09/28 22:46:10 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB1000%2F10%2F10,auth=https://authenticate.blomp.com/,tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me": Can't find AuthVersion in AuthUrl - set explicitly
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You need some more quotes around the : in the URL

```
rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000%2F10%2F10,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
```

**Comment by Spy-God** [comment]
> You need some more quotes around the : in the URL
> 
> ```
> rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000%2F10%2F10,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
> ```

The errors changed to bad request 



┌─[Lucifer@termux]─[~]
└──╼  

rclone ls
':swift,user=spygoddd@proton.me,key=DOB2003%2F09%2F05,auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:"spygoddd@proton.me" 

2025/09/29 12:17:26 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB2003%2F09%2F05,auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:\"spygoddd@proton.me\"": Bad Request

┌─[Lucifer@termux]─[~]
└──╼  
rclone ls ':swift,user=spygoddd@proton.me,key=DOB2003%2F09%2F05,auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'

2025/09/29 12:17:59 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB2003%2F09%2F05,auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me": Bad Request

┌─[Lucifer@termux]─[~]
└──╼                                                  29/Sep/25  Mon 05:48  PM

**Comment by ncw** [comment]
I suggest you make it work first with a config file.

It can then be converted into a config string very easily as long as you are careful with the quoting.

**Comment by Spy-God** [comment]
> I suggest you make it work first with a config file.
> 
> It can then be converted into a config string very easily as long as you are careful with the quoting.

It works with my config file but fails to work with inline config 

My config file 


[Blomping]
type = swift
user = spygoddd@proton.me
key = DOB2003/09/05
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2

This works when used like this 

 rclone ls Blomping:spygoddd@proton.me

But inline config keeps failing which i absolutely need.

**Comment by ncw** [comment]
This should work then.


    rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000/10/10,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'

Don't know why you had the / as %2f

**Comment by Spy-God** [comment]
> This should work then.
> 
> ```
> rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000/10/10,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
> ```
> 
> Don't know why you had the / as %2f



I also dont get why it isnt working thats why i thought  it might be rclone that has a issue with swift type.. 
  This place is my last hope for getting this to work... 


┌─[Lucifer@termux]─[~]
└──╼  rclone ls ':swift,user=spygoddd@proton.me,key=DOB1000/10/10,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
2025/09/29 19:13:48 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB1000/10/10,auth=\"https://authenticate.blomp.com/\",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me": HTTP Error: 404: 404 Not Found

┌─[Lucifer@termux]─[~]
└──╼  rclone ls ':swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
2025/09/29 19:14:21 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=\"https://authenticate.blomp.com/\",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me": HTTP Error: 404: 404 Not Found

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd Blomping:spygoddd@proton.me                                             0 2000-01-01 00:00:00        -1 Apple Music                                      0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others

┌─[Lucifer@termux]─[~]
└──╼  cat .config/rclone/rclone.conf            30/Sep/25  Tue 12:44  AM

[blomp_alias]
type = alias
remote = Blomping:spygoddd@proton.me

[Blomping]
type = swift
user = spygoddd@proton.me
key = DOB2003/09/05
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2





┌─[Lucifer@termux]─[~]
└──╼  rclone lsd ':swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth="https://authenticate.blomp.com/",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me'
2025/09/29 19:15:28 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=\"https://authenticate.blomp.com/\",tenant=storage,auth_version=2,endpoint_type=public,env_auth=false:spygoddd@proton.me": HTTP Error: 404: 404 Not Found

┌─[Lucifer@termux]─[~]
└──╼                                           30/Sep/25  Tue 12:45  AM




P.S: let me know if you want any other info from me i will gladly let you know, i just want inline config to work for blomp cloud storage...

**Comment by ncw** [comment]
> [Blomping]
> type = swift
> user = spygoddd@proton.me
> key = DOB2003/09/05
> auth = https://authenticate.blomp.com/v2.0/
> tenant = storage
> auth_version = 2

You've missed the `/v2.0/` in your connection string.

The connection string should be exactly the above with new lines replaced by , and the spaces removed. You need to put the URL in "quotes" as it has a : in.

```
rclone ls :swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me
```

If it doesn't work, double check it against the config file (I did the above on my phone so it probably has mistakes in)

**Comment by Spy-God** [comment]
I previously tried with this too. But it always ends up with this error

rclone ls :swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me
2025/09/30 02:40:58 CRITICAL: Failed to create file system for ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=https://authenticate.blomp.com/v2.0/,tenant=storage,auth_version=2:spygoddd@proton.me": Can't find AuthVersion in AuthUrl - set explicitly


I was using %2F since 

"Slashes in key are percent-encoded as %2F."

But the same error keeps ocurring if i add /v2.0/ 

But works for config.


This is how my config works

rclone -vv lsd Blomping:spygoddd@proton.me
2025/09/30 02:58:48 DEBUG : rclone: Version "v1.71.1-termux" starting with parameters ["rclone" "-vv" "lsd" "Blomping:spygoddd@proton.me"]
2025/09/30 02:58:48 DEBUG : Creating backend with remote "Blomping:spygoddd@proton.me"
2025/09/30 02:58:48 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2025/09/30 02:58:49 DEBUG : Swift container spygoddd@proton.me: Auto set use_segments_container to false
           0 2000-01-01 00:00:00        -1 Apple Music
           0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
2025/09/30 02:58:53 DEBUG : 6 go routines active

Why would this error occur when i am already passing everything thta is in my config.

Can't find AuthVersion in AuthUrl - set explicitly

My config which works

```
[Cosmic Slayer]
type = mega
user = spygodd@protonmail.com
pass = fqGMgA1Pp7ad6YmvLBpjmyjwtKBv247E-Q2GN_w
debug = true
hard_delete = true

[Divine Slayer]
type = mega
user = onlyforutube377@gmail.com
pass = brkavVzHcc3HlmDIoiQyDzchae5cVW4p2JgKKvU
debug = true
hard_delete = true

[Eternal Slayer]
type = mega
user = megaslayer344@gmail.com
pass = nHiBk1FqAEq02z_L5Xfu8B3SeY2-vIgUnePh2RA
hard_delete = true

[Heaven Slayer]
type = mega
user = bhawanishankarpandey@proton.me
pass = WRjhCbYw5Ucec3RV7eltwALWBGCoBoWEK2BRrCbT
debug = true
hard_delete = true

[Earthly Slayer]
type = mega
user = spygoddd@proton.me
pass = wzrFVYPfqhSdJkla7fweMA3FBoAjVgE1N36txWY
debug = true
hard_delete = true

[blomp_alias]
type = alias
remote = Blomping:spygoddd@proton.me

[Blomping]
type = swift
user = spygoddd@proton.me
key = DOB2003/09/05
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2
```

**Comment by Spy-God** [comment]
It finally worked.

rclone -vv lsd ':swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me'
2025/09/30 06:19:23 DEBUG : rclone: Version "v1.71.1-termux" starting with parameters ["rclone" "-vv" "lsd" ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"]
2025/09/30 06:19:23 DEBUG : Creating backend with remote ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"
2025/09/30 06:19:23 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2025/09/30 06:19:23 DEBUG : :swift: detected overridden config - adding "{LE_Sy}" suffix to name
2025/09/30 06:19:28 DEBUG : Swift container spygoddd@proton.me: Auto set use_segments_container to false
2025/09/30 06:19:28 DEBUG : fs cache: renaming cache item ":swift,user=spygoddd@proton.me,key=DOB2003/09/05,auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me" to be canonical ":swift{LE_Sy}:spygoddd@proton.me"
           0 2000-01-01 00:00:00        -1 Apple Music
           0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
           0 2000-01-01 00:00:00        -1 restic-repo
2025/09/30 06:19:32 DEBUG : 6 go routines active


But i will be keeping this issue open for now because i am trying to integrate it into my backup script and i might need some help again and it will be related to rclone ,so its still a proper place.

**Comment by Spy-God** [comment]
Script worked too thanks again.

**Comment by ncw** [comment]
> It finally worked

Hooray!

The connection strings are extremely logical but very fiddly.

Maybe I should do a `rclone config string remote:` to make them for you.

**Comment by Spy-God** [comment]
> > It finally worked
> 
> Hooray!
> 
> The connection strings are extremely logical but very fiddly.
> 
> Maybe I should do a `rclone config string remote:` to make them for you.

Thanks that would be lovely... And you have my gratitude to bear with me untill i got it right...

**Comment by Spy-God** [comment]
Thanks again let me know once its added as a  feature.. Or i will keep an eye on it myself.. 

Thanks again.

**Comment by ncw** [comment]
I added ``rclone config string remote:` for making connection strings which would have made everyone's life easier here!

**Comment by Spy-God** [comment]
> I added ``rclone config string remote:` for making connection strings which would have made everyone's life easier here!

I just tried it out but the response seems to be odd.

```

┌─[Lucifer@termux]─[~]
└──╼  rclone --version                                 02/Oct/25  Thu 10:48  PM
rclone v1.72.0-DEV
- os/version: unknown
- os/kernel: 6.6.30-android15-8-o-g42804ac7db66-4k (aarch64)
- os/type: android
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.25.0
- go/linking: dynamic
- go/tags: none

┌─[Lucifer@termux]─[~]
└──╼  rclone config string --help                      02/Oct/25  Thu 10:49  PM
zsh: correct 'config' to '.config' [nyae]? n
Print a connection string for a single remote.

The [connection strings](/docs/#connection-strings) can be used
wherever a remote is needed and can be more convenient than using the
config file, especially if using the RC API.

Backend parameters may be provided to the command also.

Example:

```sh
$ rclone config string s3:rclone --s3-no-check-bucket
:s3,access_key_id=XXX,no_check_bucket,provider=AWS,region=eu-west-2,secret_access_key=YYY:rclone
```

**NB** the strings are not quoted for use in shells (eg bash,
powershell, windows cmd). Most will work if enclosed in "double
quotes", however connection strings that contain double quotes will
require further quoting which is very shell dependent.

Usage:
  rclone config string <remote> [flags]

Flags:
  -h, --help   help for string

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

┌─[Lucifer@termux]─[~]
└──╼  rclone config string Blomping                    02/Oct/25  Thu 10:49  PM
zsh: correct 'config' to '.config' [nyae]? n
:local:Blomping

┌─[Lucifer@termux]─[~]
└──╼  rclone config show Blomping                      02/Oct/25  Thu 10:50  PM
zsh: correct 'config' to '.config' [nyae]? n
[Blomping]
type = swift
user = spygoddd@proton.me
key = HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2

┌─[Lucifer@termux]─[~]
└──╼  rclone config file                               02/Oct/25  Thu 10:50  PM
zsh: correct 'config' to '.config' [nyae]? n
Configuration file is stored at:
/data/data/com.termux/files/home/.config/rclone/rclone.conf
```

**Comment by Spy-God** [comment]
> I added ``rclone config string remote:` for making connection strings which would have made everyone's life easier here!

i just gave it a shot but the response seems to be the same each time


┌─[Lucifer@termux]─[~]
└──╼  rclone --version                                 02/Oct/25  Thu 10:48  PM
rclone v1.72.0-DEV
- os/version: unknown
- os/kernel: 6.6.30-android15-8-o-g42804ac7db66-4k (aarch64)
- os/type: android
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.25.0
- go/linking: dynamic
- go/tags: none

┌─[Lucifer@termux]─[~]
└──╼  rclone config string --help                      02/Oct/25  Thu 10:49  PM
zsh: correct 'config' to '.config' [nyae]? n
Print a connection string for a single remote.

The [connection strings](/docs/#connection-strings) can be used
wherever a remote is needed and can be more convenient than using the
config file, especially if using the RC API.

Backend parameters may be provided to the command also.

Example:

```sh
$ rclone config string s3:rclone --s3-no-check-bucket
:s3,access_key_id=XXX,no_check_bucket,provider=AWS,region=eu-west-2,secret_access_key=YYY:rclone
```

**NB** the strings are not quoted for use in shells (eg bash,
powershell, windows cmd). Most will work if enclosed in "double
quotes", however connection strings that contain double quotes will
require further quoting which is very shell dependent.

Usage:
  rclone config string <remote> [flags]

Flags:
  -h, --help   help for string

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

┌─[Lucifer@termux]─[~]
└──╼  rclone config string Blomping                    02/Oct/25  Thu 10:49  PM
zsh: correct 'config' to '.config' [nyae]? n
:local:Blomping

┌─[Lucifer@termux]─[~]
└──╼  rclone config show Blomping                      02/Oct/25  Thu 10:50  PM
zsh: correct 'config' to '.config' [nyae]? n
[Blomping]
type = swift
user = spygoddd@proton.me
key = HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2

┌─[Lucifer@termux]─[~]
└──╼  rclone config file                               02/Oct/25  Thu 10:50  PM
zsh: correct 'config' to '.config' [nyae]? n
Configuration file is stored at:
/data/data/com.termux/files/home/.config/rclone/rclone.conf

**Comment by ncw** [comment]
> rclone config string Blomping

You forgot the : on the end. Hopefully adding it will work.

    rclone config string Blomping:

**Comment by Spy-God** [comment]
We had made one inconfig string work before which was this exactly.

```

rclone -vv lsd ':swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me'

```

But config string seems to give me different response.

rclone -vv lsd ':swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me'
2025/10/02 19:15:56 DEBUG : rclone: Version "v1.72.0-DEV" starting with parameters ["rclone" "-vv" "lsd" ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"]
2025/10/02 19:15:56 DEBUG : Creating backend with remote ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"
2025/10/02 19:15:56 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2025/10/02 19:15:56 DEBUG : :swift: detected overridden config - adding "{v5-fS}" suffix to name
2025/10/02 19:15:58 DEBUG : Swift container spygoddd@proton.me: Auto set use_segments_container to false
2025/10/02 19:15:58 DEBUG : fs cache: renaming cache item ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me" to be canonical ":swift{v5-fS}:spygoddd@proton.me"
           0 2000-01-01 00:00:00        -1 Apple Music
           0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
           0 2000-01-01 00:00:00        -1 restic-repo
2025/10/02 19:16:02 DEBUG : 6 go routines active

┌─[Lucifer@termux]─[~]
└──╼  rclone config string Blomping:                                                 03/Oct/25  Fri 12:46  AM
zsh: correct 'config' to '.config' [nyae]? n
:swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':

┌─[Lucifer@termux]─[~]
└──╼  rclone --vv lsd ':swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':'
zsh: parse error near `)'

┌─[Lucifer@termux]─[~]
└──╼  rclone --vv lsd :swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':                                                     Error: unknown command ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

2025/10/02 19:16:49 NOTICE: Fatal error: unknown command ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:" for "rclone"

┌─[Lucifer@termux]─[~]
└──╼  rclone --vv lsd :swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':                                                     Error: unknown command ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

2025/10/02 19:17:25 NOTICE: Fatal error: unknown command ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:" for "rclone"

┌─[Lucifer@termux]─[~]
└──╼                                                                                03/Oct/25  Fri 12:48  AM

**Comment by Spy-God** [comment]
I tried that string command with ny one other remote(mega) it worked fine on it.


┌─[Lucifer@termux]─[~]
└──╼  rclone config string "Earthly Slayer:"                                        03/Oct/25  Fri 01:43  AM
zsh: correct 'config' to '.config' [nyae]? n
:mega,debug='true',hard_delete='true',pass='wzrFVYPfqhSdJkla7fweMA3FBoAjVgE1N36txWY',user='spygoddd@proton.me':

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd :mega,debug='true',hard_delete='true',pass='wzrFVYPfqhSdJkla7fweMA3FBoAjVgE1N36txWY',user='spygoddd@proton.me':                                                                                                         
┌─[Lucifer@termux]─[~]
└──╼  rclone config string "Cosmic Slayer:"                                          03/Oct/25  Fri 01:45  AM
zsh: correct 'config' to '.config' [nyae]? n
:mega,debug='true',hard_delete='true',pass='fqGMgA1Pp7ad6YmvLBpjmyjwtKBv247E-Q2GN_w',user='spygodd@protonmail.com':

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd :mega,debug='true',hard_delete='true',pass='fqGMgA1Pp7ad6YmvLBpjmyjwtKBv247E-Q2GN_w',user='spygodd@protonmail.com':                                                                                                               -1 2025-09-30 21:09:48        -1 restic-repo

┌─[Lucifer@termux]─[~]
└──╼  rclone config string  "Blomping:"                                              03/Oct/25  Fri 01:45  AM zsh: correct 'config' to '.config' [nyae]? n
:swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd :swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':                                                          2025/10/02 20:16:20 CRITICAL: Failed to create file system for ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:": Can't find AuthVersion in AuthUrl - set explicitly

┌─[Lucifer@termux]─[~]
└──╼                                                                                03/Oct


It seems blomp cloud storage and in short swift backend ones are causing a issue... 

rclone config string Blomping:

Since its output seems to be giving out error...

**Comment by ncw** [comment]
```
> rclone config string Blomping:
:swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':
```

The config string here is correct but it isn't escaped for the shell.

It is worth looking at the help

```
$ rclone config string --help
```

> Print a connection string for a single remote.
> 
> The [connection strings](/docs/#connection-strings) can be used
> wherever a remote is needed and can be more convenient than using the
> config file, especially if using the RC API.
> 
> Backend parameters may be provided to the command also.
> 
> Example:
> 
> ```sh
> $ rclone config string s3:rclone --s3-no-check-bucket
> :s3,access_key_id=XXX,no_check_bucket,provider=AWS,region=eu-west-2,secret_access_key=YYY:rclone
> ```
> 
> **NB** the strings are not quoted for use in shells (eg bash,
> powershell, windows cmd). Most will work if enclosed in "double
> quotes", however connection strings that contain double quotes will
> require further quoting which is very shell dependent.
> 
> Usage:
>   rclone config string <remote> [flags]
> 
> Flags:
>   -h, --help   help for string
> 

Which indicates quoting with double quotes " is the thing to do.

Hopefully this should work

```
rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':"
```

Shell quoting is complicated alas!

**Comment by ncw** [comment]
@Spy-God - I pushed another update to `rclone config strings` - it was using too many quotes!

**Comment by Spy-God** [comment]
I updated my rclone but the rclone config string still fails.


┌─[Lucifer@termux]─[~]
└──╼  rclone config string "Blomping:"          03/Oct/25  Fri 09:17  PM
zsh: correct 'config' to '.config' [nyae]? n
:swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':"                                                                                                                                                2025/10/03 15:47:47 ERROR : error listing: container listing failed: Operation forbidden
2025/10/03 15:47:47 NOTICE: Failed to lsd with 2 errors: last error was: container listing failed: Operation forbidden

┌─[Lucifer@termux]─[~]
└──╼                                           03/Oct/25  Fri 09:17  PM

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd :swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':                                                                 2025/10/03 15:48:02 CRITICAL: Failed to create file system for ":swift,auth=https://authenticate.blomp.com/v2.0/,auth_version=2,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),tenant=storage,user=spygoddd@proton.me:": Can't find AuthVersion in AuthUrl - set explicitly

┌─[Lucifer@termux]─[~]
└──╼  rclone lsd Blomping:spygoddd@proton.me                                             0 2000-01-01 00:00:00        -1 Apple Music                                      0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
           0 2000-01-01 00:00:00        -1 restic-repo

┌─[Lucifer@termux]─[~]
└──╼  cat .config/rclone/rclone.conf            03/Oct/25  Fri 09:18  PM
[Blomping]
type = swift
user = spygoddd@proton.me
key = HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)
auth = https://authenticate.blomp.com/v2.0/
tenant = storage
auth_version = 2


┌─[Lucifer@termux]─[~]
└──╼  rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':"
2025/10/03 15:49:17 ERROR : error listing: container listing failed: Operation forbidden
2025/10/03 15:49:17 NOTICE: Failed to lsd with 2 errors: last error was: container listing failed: Operation forbidden

┌─[Lucifer@termux]─[~]
└──╼                                           03/Oct/25

The only inline working config i got for Swift remote is this one, let me know if its of any help.. 

 'rclone::swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me/restic-repo'
 
i am currently using it in ny backup script and it works. 

rclone -vv lsd ':swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth="https://authenticate.blomp.com/v2.0/",tenant=storage,auth_version=2:spygoddd@proton.me'
2025/10/03 16:05:40 DEBUG : rclone: Version "v1.72.0-DEV" starting with parameters ["rclone" "-vv" "lsd" ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"]
2025/10/03 16:05:40 DEBUG : Creating backend with remote ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me"
2025/10/03 16:05:40 DEBUG : Using config file from "/data/data/com.termux/files/home/.config/rclone/rclone.conf"
2025/10/03 16:05:40 DEBUG : :swift: detected overridden config - adding "{v5-fS}" suffix to name
2025/10/03 16:05:42 DEBUG : Swift container spygoddd@proton.me: Auto set use_segments_container to false
2025/10/03 16:05:42 DEBUG : fs cache: renaming cache item ":swift,user=spygoddd@proton.me,key=HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z),auth=\"https://authenticate.blomp.com/v2.0/\",tenant=storage,auth_version=2:spygoddd@proton.me" to be canonical ":swift{v5-fS}:spygoddd@proton.me"
           0 2000-01-01 00:00:00        -1 Apple Music
           0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
           0 2000-01-01 00:00:00        -1 restic-repo
2025/10/03 16:05:47 DEBUG : 6 go routines active

**Comment by ncw** [comment]
> rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':" 2025/10/03 15:47:47 ERROR : error listing: container listing failed: Operation forbidden

This is missing the container name - blomp doesn't allow listing the container root.

So

    rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version='2',key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant='storage',user='spygoddd@proton.me':spygoddd@proton.me"

It looks correct in your backup script

**Comment by Spy-God** [comment]
I just wanted to say that rclone config command that you added works for mega (personally tested) but fails for swift based cloud backend(blomp cloud storage in my case),

I got that rclone lsd command right in backup script after a half month of tweaking with it(quite litterally) including your help for the last week... It would be very hard for normal users to make inline config work if rclone config also gives them wrong output..

**Comment by ncw** [comment]
> I just wanted to say that rclone config command that you added works for mega (personally tested) 

Great

> but fails for swift based cloud backend(blomp cloud storage in my case),

You need to add the bucket to the config to make blomp work, so given that this worked

    rclone lsd Blomping:spygoddd@proton.me

then this will generate the entire config string needed

    rclone config string Blomping:spygoddd@proton.me

> I got that rclone lsd command right in backup script after a half month of tweaking with it(quite litterally) including your help for the last week... It would be very hard for normal users to make inline config work if rclone config also gives them wrong output..

I'm pretty confident the output is correct. However if the input is not correct the output won't be!

**Comment by Spy-God** [comment]
Looks like i was just missing the email it works perfectly now..


└──╼  rclone config string Blomping:spygoddd@proton.me
:swift,auth='https://authenticate.blomp.com/v2.0/',auth_version=2,key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant=storage,user=spygoddd@proton.me:spygoddd@proton.me

└──╼  rclone lsd ":swift,auth='https://authenticate.blomp.com/v2.0/',auth_version=2,key='HpoghC%f=pURk+rQGh5Dy9PrK8WMaq3k933Ks4z)',tenant=storage,user=spygoddd@proton.me:spygoddd@proton.me"                                                              0 2000-01-01 00:00:00        -1 Apple Music                                      0 2000-01-01 00:00:00        -1 Flac
           0 2000-01-01 00:00:00        -1 MP3
           0 2000-01-01 00:00:00        -1 Others
           0 2000-01-01 00:00:00        -1 restic-repo



Thanks...
